import { Navigation } from "@/components/Navigation";
import { Footer } from "@/components/Footer";
import { AnimatedHero } from "@/components/AnimatedHero";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  ShieldCheck,
  ArrowRight,
  Zap,
  Lock,
  Search,
  Network,
  FileCheck,
} from "lucide-react";
import Link from "next/link";

export const metadata = {
  title: "Proof Explorer | Settler",
  description: "Drill into cryptographic evidence chains for financial reconciliation outcomes.",
};

const proofStates = [
  { label: "Execution Graph Hash", value: "8aF9...3b21" },
  { label: "Merkle Root Verified", value: "True" },
  { label: "Policy Context", value: "v2.4.1 (Active)" },
  { label: "Audit State", value: "Terminal" },
];

export default function ProofExplorerMarketingPage() {
  return (
    <div className="min-h-screen bg-background">
      <Navigation />

      <AnimatedHero
        badge="Platform Feature"
        title="Proof Explorer"
        description="Inspect the Trust Graph of your financial operations. Every match is an link in an immutable chain of evidence, providing audit-grade certainty for every transaction."
      />

      <section className="py-24 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto -mt-16">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-start">
          <div className="space-y-10 pt-8">
            <div className="space-y-4">
              <h2 className="text-4xl font-bold tracking-tight italic">
                Beyond Logs: Mathematical Evidence
              </h2>
              <p className="text-lg text-muted-foreground font-medium leading-relaxed max-w-xl">
                Logs can be altered. Settler's Proof Explorer provides a visual interface for the
                underlying cryptographic proof graph generated by every reconciliation run.
              </p>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
              {[
                {
                  icon: Search,
                  title: "Deep Inspection",
                  desc: "Drill into specific transaction pairs to view their signed hashes.",
                },
                {
                  icon: Network,
                  title: "Graph Lineage",
                  desc: "Visualize the dependency chain of data snapshots and final results.",
                },
                {
                  icon: FileCheck,
                  title: "Audit Export",
                  desc: "Generate machine-readable evidence packages for compliance review.",
                },
                {
                  icon: Lock,
                  title: "SHA-256 Anchors",
                  desc: "Immutable hashes ensure no record was modified post-reconciliation.",
                },
              ].map((item) => (
                <div key={item.title} className="space-y-3">
                  <div className="h-10 w-10 rounded-lg bg-primary/10 text-primary flex items-center justify-center">
                    <item.icon className="h-5 w-5" />
                  </div>
                  <h3 className="text-sm font-bold">{item.title}</h3>
                  <p className="text-xs text-muted-foreground font-medium leading-relaxed">
                    {item.desc}
                  </p>
                </div>
              ))}
            </div>

            <Button asChild size="lg" className="h-14 px-8 text-lg font-bold group">
              <Link href="/signup">
                Start Exploring
                <ArrowRight className="ml-2 h-4 w-4 group-hover:translate-x-1 transition-transform" />
              </Link>
            </Button>
          </div>

          <div className="relative group lg:sticky lg:top-32">
            <div className="absolute -inset-1 bg-gradient-to-r from-teal-500 to-primary rounded-2xl blur opacity-20 group-hover:opacity-40 transition-opacity" />
            <Card className="relative border-border/60 bg-card overflow-hidden h-full flex flex-col shadow-2xl">
              <CardHeader className="border-b border-border/40 bg-muted/30 pb-6">
                <div className="flex items-center justify-between mb-4">
                  <Badge className="bg-primary/10 text-primary border-primary/20 text-[10px] font-black uppercase tracking-[0.2em] px-3 py-1">
                    Proof Node #9821
                  </Badge>
                  <span className="text-[10px] font-mono text-muted-foreground">
                    STATE: VERIFIED
                  </span>
                </div>
                <CardTitle className="text-lg flex items-center gap-2">
                  <Search size={18} className="text-primary" />
                  Transaction Lineage
                </CardTitle>
              </CardHeader>
              <CardContent className="p-8 space-y-8">
                {/* Visual graph mockup */}
                <div className="relative h-48 bg-muted/20 rounded-xl border border-dashed border-border/60 flex items-center justify-center p-4">
                  <div className="flex items-center gap-8 z-10">
                    <div className="h-12 w-12 rounded bg-slate-900 border border-white/10 flex items-center justify-center shadow-lg transform -rotate-6">
                      <Lock size={20} className="text-primary" />
                    </div>
                    <div className="h-0.5 w-16 bg-primary/40 relative">
                      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 h-4 w-4 rounded-full bg-primary flex items-center justify-center border-4 border-card">
                        <Zap size={8} className="text-white fill-current" />
                      </div>
                    </div>
                    <div className="h-12 w-12 rounded bg-slate-900 border border-white/10 flex items-center justify-center shadow-lg transform rotate-6">
                      <ShieldCheck size={20} className="text-primary" />
                    </div>
                  </div>
                  <div className="absolute inset-0 opacity-10 bg-[radial-gradient(circle,rgba(20,184,166,0.3)_0%,transparent_70%)]" />
                </div>

                <div className="grid grid-cols-2 gap-4">
                  {proofStates.map((state) => (
                    <div
                      key={state.label}
                      className="space-y-1.5 p-3 rounded-lg border border-border/40 bg-muted/10"
                    >
                      <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest leading-none">
                        {state.label}
                      </p>
                      <p className="text-xs font-bold text-foreground font-mono">{state.value}</p>
                    </div>
                  ))}
                </div>

                <div className="p-4 rounded-xl bg-slate-950 text-[10px] font-mono leading-relaxed text-slate-400">
                  <p className="text-primary mb-1">{`{`}</p>
                  <p className="pl-4 italic">&quot;merkle_root&quot;: &quot;0x8aF9...3b21&quot;,</p>
                  <p className="pl-4">&quot;evidence_type&quot;: &quot;MATCH_CONFORMATION&quot;,</p>
                  <p className="pl-4">&quot;verification_date&quot;: &quot;2026-03-19&quot;</p>
                  <p className="text-primary">{`}`}</p>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      {/* Trust Grid */}
      <section className="py-24 border-y border-border/40 bg-muted/10">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16 space-y-4">
            <h2 className="text-3xl font-bold italic tracking-tight underline underline-offset-8">
              Trust Ecosystem
            </h2>
            <p className="text-muted-foreground font-medium max-w-xl mx-auto">
              Settler provides a unified source of truth across multiple financial adapters.
            </p>
          </div>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 sm:gap-8">
            {[
              "Stripe",
              "Adyen",
              "Shopify",
              "TigerBeetle",
              "Plaid",
              "Brex",
              "Quickbooks",
              "SAP",
            ].map((item) => (
              <div
                key={item}
                className="flex items-center justify-center h-20 rounded-2xl bg-card border border-border/60 grayscale-[0.5] opacity-60 hover:grayscale-0 hover:opacity-100 transition-all font-bold text-slate-400 text-sm italic"
              >
                {item}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pre-footer CTA */}
      <section className="py-24 px-4 sm:px-6 lg:px-8 max-w-4xl mx-auto text-center">
        <ShieldCheck className="h-16 w-16 text-primary mx-auto mb-8 opacity-40 shadow-2xl" />
        <h2 className="text-3xl md:text-5xl font-bold mb-6 tracking-tight italic">
          Audit Harder. Worry Less.
        </h2>
        <p className="text-xl text-muted-foreground mb-10 leading-relaxed font-medium">
          Eliminate the manual evidence collection process and provide auditors with a direct,
          verifiable feed of data integrity.
        </p>
        <div className="flex flex-col sm:flex-row gap-4 justify-center">
          <Button asChild size="lg" className="h-14 px-8 text-lg font-bold">
            <Link href="/signup">Create Free Account</Link>
          </Button>
          <Button asChild variant="outline" size="lg" className="h-14 px-8 text-lg font-bold">
            <Link href="/docs/replay-lab">Technical Docs</Link>
          </Button>
        </div>
      </section>

      <Footer />
    </div>
  );
}
