config-variables:
  - "ENABLE_AUTO_SYNC"
  - ".*"

secrets:
  - "PUBLIC_MIRROR_GIT_USERNAME"
  - "PUBLIC_MIRROR_REPO_URL"
  - "PUBLIC_MIRROR_GIT_TOKEN"
  - "STAGING_DATABASE_URL"
  - "SUPABASE_DB_URL"
  - "SUPABASE_DB_URL_STAGING"
  - "SUPABASE_URL_STAGING"
  - "SUPABASE_DB_PASSWORD"
  - "SUPABASE_DB_PASSWORD_STAGING"
  - "TURBO_TOKEN"
  - "TURBO_TEAM"
  - "STAGING_JWT_SECRET"
  - "STAGING_ENCRYPTION_KEY"
  - "STAGING_URL"
  - "JWT_SECRET"
  - "ENCRYPTION_KEY"
  - "PRODUCTION_URL"
  - "DEPENDABOT_ALERTS_EXPORT_B64"
  - "DIRECT_URL"
  - "DATABASE_URL"
  - "SUPABASE_URL"
  - "UPSTASH_REDIS_REST_URL"
  - "UPSTASH_REDIS_REST_TOKEN"
  - "GITHUB_TOKEN"
  - ".*"
