// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// During Prisma generation, DATABASE_URL is not required.
// Prisma generate only needs the schema file, not a database connection.
// We provide a placeholder URL if DATABASE_URL is not set.
// Note: We use process.env.DATABASE_URL directly instead of env() helper
// to avoid PrismaConfigEnvError when DATABASE_URL is missing during build.
const databaseUrl = process.env.DATABASE_URL || "postgresql://placeholder:placeholder@localhost:5432/placeholder";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
