apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "settler.fullname" . }}-config
data:
  NODE_ENV: {{ .Values.env.NODE_ENV | quote }}
  API_PORT: {{ .Values.env.API_PORT | quote }}
  WEB_PORT: {{ .Values.env.WEB_PORT | quote }}
  SCHEDULER_ENABLED: {{ .Values.env.SCHEDULER_ENABLED | quote }}
