export type ConsoleFeatureDomain =
  | "overview"
  | "reconciliations"
  | "audits"
  | "policies"
  | "control-plane"
  | "analytics"
  | "diagnostics"
  | "developer"
  | "billing"
  | "settings"
  | "site"
  | "admin";

export type ConsoleMaturityClass =
  | "runtime-operational"
  | "runtime-degraded-without-env"
  | "runtime-degraded-without-tenant"
  | "runtime-degraded-without-provider"
  | "informational"
  | "thin"
  | "admin-only";

export type RuntimeDependencyClass = "none" | "supabase" | "stripe" | "providers" | "hybrid";

export type ConsoleNavSection =
  | "Operations"
  | "Intelligence"
  | "Developer"
  | "Settings"
  | "Enterprise"
  | "Administration";

export interface ConsoleRouteEntry {
  href: string;
  label: string;
  section: ConsoleNavSection;
  domain: ConsoleFeatureDomain;
  maturity: ConsoleMaturityClass;
  runtimeDependency: RuntimeDependencyClass;
  authRequired: boolean;
  tenantScopeRequired: boolean;
  roleRestriction: "none" | "super-admin";
  envRequired: boolean;
  databaseRequired: boolean;
  stripeRequired: boolean;
  supabaseRequired: boolean;
  externalProviderRequired: boolean;
  explicitDisclosureRequired: boolean;
  degradedBehavior: string;
  navTreatment: "primary" | "secondary" | "restricted";
  ctaRestrictions: "none" | "read-only" | "disabled";
  dataMode: "operational" | "informational" | "synthetic" | "restricted";
}

export const CONSOLE_ROUTE_REGISTRY: readonly ConsoleRouteEntry[] = [
  {
    href: "/console",
    label: "Dashboard",
    section: "Operations",
    domain: "overview",
    maturity: "runtime-degraded-without-env",
    runtimeDependency: "hybrid",
    authRequired: true,
    tenantScopeRequired: true,
    roleRestriction: "none",
    envRequired: true,
    databaseRequired: true,
    stripeRequired: false,
    supabaseRequired: true,
    externalProviderRequired: false,
    explicitDisclosureRequired: true,
    degradedBehavior: "Renders shell + limited cards with explicit runtime dependency notice.",
    navTreatment: "primary",
    ctaRestrictions: "read-only",
    dataMode: "operational",
  },
  {
    href: "/console/reconciliations",
    label: "Reconciliations",
    section: "Operations",
    domain: "reconciliations",
    maturity: "runtime-operational",
    runtimeDependency: "hybrid",
    authRequired: true,
    tenantScopeRequired: true,
    roleRestriction: "none",
    envRequired: true,
    databaseRequired: true,
    stripeRequired: false,
    supabaseRequired: true,
    externalProviderRequired: false,
    explicitDisclosureRequired: false,
    degradedBehavior: "Falls back to no-run state until tenant scoped run history is available.",
    navTreatment: "primary",
    ctaRestrictions: "none",
    dataMode: "operational",
  },
  {
    href: "/console/runs",
    label: "Runs",
    section: "Operations",
    domain: "reconciliations",
    maturity: "runtime-operational",
    runtimeDependency: "hybrid",
    authRequired: true,
    tenantScopeRequired: true,
    roleRestriction: "none",
    envRequired: true,
    databaseRequired: true,
    stripeRequired: false,
    supabaseRequired: true,
    externalProviderRequired: false,
    explicitDisclosureRequired: false,
    degradedBehavior: "Shows persisted run history and execution state for the current tenant.",
    navTreatment: "primary",
    ctaRestrictions: "none",
    dataMode: "operational",
  },
  {
    href: "/console/exceptions",
    label: "Exceptions",
    section: "Operations",
    domain: "reconciliations",
    maturity: "runtime-operational",
    runtimeDependency: "supabase",
    authRequired: true,
    tenantScopeRequired: true,
    roleRestriction: "none",
    envRequired: true,
    databaseRequired: true,
    stripeRequired: false,
    supabaseRequired: true,
    externalProviderRequired: false,
    explicitDisclosureRequired: false,
    degradedBehavior: "Shows run-scoped exception decisions and operator workflow state.",
    navTreatment: "primary",
    ctaRestrictions: "none",
    dataMode: "operational",
  },
  {
    href: "/console/audits",
    label: "Audits",
    section: "Operations",
    domain: "audits",
    maturity: "runtime-degraded-without-tenant",
    runtimeDependency: "supabase",
    authRequired: true,
    tenantScopeRequired: true,
    roleRestriction: "none",
    envRequired: true,
    databaseRequired: true,
    stripeRequired: false,
    supabaseRequired: true,
    externalProviderRequired: false,
    explicitDisclosureRequired: true,
    degradedBehavior: "Shows explicit tenant scope requirement before rendering evidence tables.",
    navTreatment: "secondary",
    ctaRestrictions: "read-only",
    dataMode: "operational",
  },
  {
    href: "/console/proof-explorer",
    label: "Proof Explorer",
    section: "Operations",
    domain: "audits",
    maturity: "runtime-degraded-without-tenant",
    runtimeDependency: "supabase",
    authRequired: true,
    tenantScopeRequired: true,
    roleRestriction: "none",
    envRequired: true,
    databaseRequired: true,
    stripeRequired: false,
    supabaseRequired: true,
    externalProviderRequired: false,
    explicitDisclosureRequired: true,
    degradedBehavior:
      "Shows evidence guidance and no-proof state when tenant context is unavailable.",
    navTreatment: "secondary",
    ctaRestrictions: "read-only",
    dataMode: "operational",
  },
  {
    href: "/console/policies",
    label: "Policies",
    section: "Operations",
    domain: "policies",
    maturity: "runtime-operational",
    runtimeDependency: "supabase",
    authRequired: true,
    tenantScopeRequired: true,
    roleRestriction: "none",
    envRequired: true,
    databaseRequired: true,
    stripeRequired: false,
    supabaseRequired: true,
    externalProviderRequired: false,
    explicitDisclosureRequired: false,
    degradedBehavior: "Uses policy defaults when persistent store is unavailable.",
    navTreatment: "primary",
    ctaRestrictions: "none",
    dataMode: "operational",
  },
  {
    href: "/console/control-plane",
    label: "Control Plane",
    section: "Operations",
    domain: "control-plane",
    maturity: "runtime-operational",
    runtimeDependency: "hybrid",
    authRequired: true,
    tenantScopeRequired: true,
    roleRestriction: "none",
    envRequired: true,
    databaseRequired: true,
    stripeRequired: false,
    supabaseRequired: true,
    externalProviderRequired: true,
    explicitDisclosureRequired: true,
    degradedBehavior: "Degrades to partial status cards when provider telemetry is missing.",
    navTreatment: "primary",
    ctaRestrictions: "read-only",
    dataMode: "operational",
  },
  {
    href: "/console/analytics",
    label: "Analytics",
    section: "Intelligence",
    domain: "analytics",
    maturity: "runtime-degraded-without-env",
    runtimeDependency: "hybrid",
    authRequired: true,
    tenantScopeRequired: true,
    roleRestriction: "none",
    envRequired: true,
    databaseRequired: true,
    stripeRequired: false,
    supabaseRequired: true,
    externalProviderRequired: false,
    explicitDisclosureRequired: true,
    degradedBehavior: "Renders limited event-derived rollups with explicit partial coverage note.",
    navTreatment: "secondary",
    ctaRestrictions: "read-only",
    dataMode: "operational",
  },
  {
    href: "/console/insights",
    label: "AI Insights",
    section: "Intelligence",
    domain: "analytics",
    maturity: "runtime-degraded-without-provider",
    runtimeDependency: "providers",
    authRequired: true,
    tenantScopeRequired: true,
    roleRestriction: "none",
    envRequired: true,
    databaseRequired: true,
    stripeRequired: false,
    supabaseRequired: true,
    externalProviderRequired: true,
    explicitDisclosureRequired: true,
    degradedBehavior: "Shows deterministic fallback insights when AI provider config is absent.",
    navTreatment: "secondary",
    ctaRestrictions: "read-only",
    dataMode: "operational",
  },
  {
    href: "/console/diagnostics",
    label: "Diagnostics",
    section: "Intelligence",
    domain: "diagnostics",
    maturity: "runtime-degraded-without-env",
    runtimeDependency: "hybrid",
    authRequired: true,
    tenantScopeRequired: false,
    roleRestriction: "none",
    envRequired: true,
    databaseRequired: false,
    stripeRequired: false,
    supabaseRequired: false,
    externalProviderRequired: false,
    explicitDisclosureRequired: true,
    degradedBehavior: "Always available, explicitly reports missing runtime contracts.",
    navTreatment: "secondary",
    ctaRestrictions: "read-only",
    dataMode: "informational",
  },
  {
    href: "/console/api-keys",
    label: "API Keys",
    section: "Developer",
    domain: "developer",
    maturity: "runtime-operational",
    runtimeDependency: "supabase",
    authRequired: true,
    tenantScopeRequired: true,
    roleRestriction: "none",
    envRequired: true,
    databaseRequired: true,
    stripeRequired: false,
    supabaseRequired: true,
    externalProviderRequired: false,
    explicitDisclosureRequired: false,
    degradedBehavior: "Read-only list when key provisioning backend is unavailable.",
    navTreatment: "secondary",
    ctaRestrictions: "read-only",
    dataMode: "operational",
  },
  {
    href: "/console/webhooks",
    label: "Webhooks",
    section: "Developer",
    domain: "developer",
    maturity: "runtime-degraded-without-provider",
    runtimeDependency: "providers",
    authRequired: true,
    tenantScopeRequired: true,
    roleRestriction: "none",
    envRequired: true,
    databaseRequired: true,
    stripeRequired: false,
    supabaseRequired: true,
    externalProviderRequired: true,
    explicitDisclosureRequired: true,
    degradedBehavior:
      "Configuration UI remains available while delivery state is shown as disconnected.",
    navTreatment: "secondary",
    ctaRestrictions: "read-only",
    dataMode: "operational",
  },
  {
    href: "/console/workflows",
    label: "Workflows",
    section: "Developer",
    domain: "developer",
    maturity: "thin",
    runtimeDependency: "hybrid",
    authRequired: true,
    tenantScopeRequired: true,
    roleRestriction: "none",
    envRequired: false,
    databaseRequired: false,
    stripeRequired: false,
    supabaseRequired: false,
    externalProviderRequired: false,
    explicitDisclosureRequired: true,
    degradedBehavior: "Displays workflow scaffolding with explicit limited-operability disclosure.",
    navTreatment: "secondary",
    ctaRestrictions: "disabled",
    dataMode: "restricted",
  },
  {
    href: "/console/billing",
    label: "Billing & Plan",
    section: "Settings",
    domain: "billing",
    maturity: "runtime-degraded-without-provider",
    runtimeDependency: "stripe",
    authRequired: true,
    tenantScopeRequired: true,
    roleRestriction: "none",
    envRequired: true,
    databaseRequired: true,
    stripeRequired: true,
    supabaseRequired: true,
    externalProviderRequired: false,
    explicitDisclosureRequired: true,
    degradedBehavior:
      "Shows plan context; payment controls disabled until Stripe runtime is configured.",
    navTreatment: "secondary",
    ctaRestrictions: "read-only",
    dataMode: "operational",
  },
  {
    href: "/console/settings",
    label: "Settings",
    section: "Settings",
    domain: "settings",
    maturity: "runtime-operational",
    runtimeDependency: "supabase",
    authRequired: true,
    tenantScopeRequired: true,
    roleRestriction: "none",
    envRequired: true,
    databaseRequired: true,
    stripeRequired: false,
    supabaseRequired: true,
    externalProviderRequired: false,
    explicitDisclosureRequired: false,
    degradedBehavior: "Read-only tenant metadata in degraded mode.",
    navTreatment: "secondary",
    ctaRestrictions: "read-only",
    dataMode: "operational",
  },
  {
    href: "/console/site",
    label: "Site Designer",
    section: "Settings",
    domain: "site",
    maturity: "runtime-degraded-without-tenant",
    runtimeDependency: "supabase",
    authRequired: true,
    tenantScopeRequired: true,
    roleRestriction: "none",
    envRequired: true,
    databaseRequired: true,
    stripeRequired: false,
    supabaseRequired: true,
    externalProviderRequired: false,
    explicitDisclosureRequired: true,
    degradedBehavior: "Shows tenant-site editing disabled until scoped tenant context resolves.",
    navTreatment: "secondary",
    ctaRestrictions: "read-only",
    dataMode: "operational",
  },
  {
    href: "/console/replay",
    label: "Replay Lab",
    section: "Enterprise",
    domain: "reconciliations",
    maturity: "thin",
    runtimeDependency: "none",
    authRequired: true,
    tenantScopeRequired: false,
    roleRestriction: "none",
    envRequired: false,
    databaseRequired: false,
    stripeRequired: false,
    supabaseRequired: false,
    externalProviderRequired: false,
    explicitDisclosureRequired: true,
    degradedBehavior: "Renders synthetic replay examples only.",
    navTreatment: "restricted",
    ctaRestrictions: "disabled",
    dataMode: "synthetic",
  },
  {
    href: "/console/audit-trail",
    label: "Audit Trail",
    section: "Enterprise",
    domain: "audits",
    maturity: "runtime-degraded-without-tenant",
    runtimeDependency: "supabase",
    authRequired: true,
    tenantScopeRequired: true,
    roleRestriction: "none",
    envRequired: true,
    databaseRequired: true,
    stripeRequired: false,
    supabaseRequired: true,
    externalProviderRequired: false,
    explicitDisclosureRequired: true,
    degradedBehavior:
      "Displays scoped audit entries and empty-state disclosure when context is missing.",
    navTreatment: "restricted",
    ctaRestrictions: "read-only",
    dataMode: "operational",
  },
  {
    href: "/console/operator",
    label: "Operator Console",
    section: "Enterprise",
    domain: "control-plane",
    maturity: "runtime-degraded-without-env",
    runtimeDependency: "hybrid",
    authRequired: true,
    tenantScopeRequired: false,
    roleRestriction: "none",
    envRequired: true,
    databaseRequired: true,
    stripeRequired: false,
    supabaseRequired: true,
    externalProviderRequired: false,
    explicitDisclosureRequired: true,
    degradedBehavior: "Returns partial control-plane payload with degraded-state banner.",
    navTreatment: "restricted",
    ctaRestrictions: "read-only",
    dataMode: "operational",
  },
  {
    href: "/console/admin/tenants",
    label: "Tenant Observability",
    section: "Administration",
    domain: "admin",
    maturity: "admin-only",
    runtimeDependency: "supabase",
    authRequired: true,
    tenantScopeRequired: false,
    roleRestriction: "super-admin",
    envRequired: true,
    databaseRequired: true,
    stripeRequired: false,
    supabaseRequired: true,
    externalProviderRequired: false,
    explicitDisclosureRequired: true,
    degradedBehavior: "Not promoted to non-admin users and fails closed.",
    navTreatment: "restricted",
    ctaRestrictions: "read-only",
    dataMode: "restricted",
  },
] as const;

export function getConsoleRouteMeta(href: string): ConsoleRouteEntry | undefined {
  return CONSOLE_ROUTE_REGISTRY.find((route) => route.href === href);
}
