"use client";

import { useState } from "react";
import { Download, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

interface CustomerStory {
  companyName: string;
  industry: string;
  challenge: string;
  solution: string;
  results: string;
  quote: string;
  metrics: {
    timeSaved: string;
    accuracy: string;
    costSavings: string;
  };
}

export function CustomerStoryGenerator() {
  const [formData, setFormData] = useState({
    companyName: "",
    industry: "",
    challenge: "",
    solution: "",
    results: "",
    timeSaved: "",
    accuracy: "",
    costSavings: "",
  });
  const [generatedStory, setGeneratedStory] = useState<CustomerStory | null>(null);

  const generateStory = () => {
    const story: CustomerStory = {
      companyName: formData.companyName || "Example Company",
      industry: formData.industry || "E-commerce",
      challenge: formData.challenge || "Manual reconciliation taking 10+ hours per week",
      solution: formData.solution || "Implemented Settler API for automated reconciliation",
      results: formData.results || "Reduced reconciliation time by 95%",
      quote: `"Settler transformed our reconciliation process. What used to take our team 10+ hours now takes 5 minutes."`,
      metrics: {
        timeSaved: formData.timeSaved || "10 hours/week",
        accuracy: formData.accuracy || "99.7%",
        costSavings: formData.costSavings || "$50,000/year",
      },
    };

    setGeneratedStory(story);
  };

  const exportStory = () => {
    if (!generatedStory) return;

    const storyText = `
# Customer Success Story: ${generatedStory.companyName}

## Company Overview
- **Company:** ${generatedStory.companyName}
- **Industry:** ${generatedStory.industry}

## The Challenge
${generatedStory.challenge}

## The Solution
${generatedStory.solution}

## Results
${generatedStory.results}

### Key Metrics
- Time Saved: ${generatedStory.metrics.timeSaved}
- Accuracy: ${generatedStory.metrics.accuracy}
- Cost Savings: ${generatedStory.metrics.costSavings}

## Customer Quote
${generatedStory.quote}

---
*Generated by Settler Customer Story Generator*
`;

    const blob = new Blob([storyText], { type: "text/markdown" });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `customer-story-${generatedStory.companyName.toLowerCase().replace(/\s+/g, "-")}.md`;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
      <Card>
        <CardHeader>
          <CardTitle>Customer Story Generator</CardTitle>
          <CardDescription>Generate customer success stories and testimonials</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div>
            <Label htmlFor="companyName">Company Name</Label>
            <Input
              id="companyName"
              value={formData.companyName}
              onChange={(e) => setFormData({ ...formData, companyName: e.target.value })}
              placeholder="Acme Corp"
            />
          </div>
          <div>
            <Label htmlFor="industry">Industry</Label>
            <Input
              id="industry"
              value={formData.industry}
              onChange={(e) => setFormData({ ...formData, industry: e.target.value })}
              placeholder="E-commerce"
            />
          </div>
          <div>
            <Label htmlFor="challenge">Challenge</Label>
            <Textarea
              id="challenge"
              value={formData.challenge}
              onChange={(e) => setFormData({ ...formData, challenge: e.target.value })}
              placeholder="Describe the customer's challenge..."
              rows={3}
            />
          </div>
          <div>
            <Label htmlFor="solution">Solution</Label>
            <Textarea
              id="solution"
              value={formData.solution}
              onChange={(e) => setFormData({ ...formData, solution: e.target.value })}
              placeholder="How Settler solved the problem..."
              rows={3}
            />
          </div>
          <div>
            <Label htmlFor="results">Results</Label>
            <Textarea
              id="results"
              value={formData.results}
              onChange={(e) => setFormData({ ...formData, results: e.target.value })}
              placeholder="Quantifiable results..."
              rows={3}
            />
          </div>
          <div className="grid grid-cols-3 gap-4">
            <div>
              <Label htmlFor="timeSaved">Time Saved</Label>
              <Input
                id="timeSaved"
                value={formData.timeSaved}
                onChange={(e) => setFormData({ ...formData, timeSaved: e.target.value })}
                placeholder="10 hours/week"
              />
            </div>
            <div>
              <Label htmlFor="accuracy">Accuracy</Label>
              <Input
                id="accuracy"
                value={formData.accuracy}
                onChange={(e) => setFormData({ ...formData, accuracy: e.target.value })}
                placeholder="99.7%"
              />
            </div>
            <div>
              <Label htmlFor="costSavings">Cost Savings</Label>
              <Input
                id="costSavings"
                value={formData.costSavings}
                onChange={(e) => setFormData({ ...formData, costSavings: e.target.value })}
                placeholder="$50K/year"
              />
            </div>
          </div>
          <Button onClick={generateStory} className="w-full">
            <Sparkles className="w-4 h-4 mr-2" />
            Generate Story
          </Button>
        </CardContent>
      </Card>

      {generatedStory && (
        <Card>
          <CardHeader>
            <div className="flex items-center justify-between">
              <CardTitle>Generated Story</CardTitle>
              <Button onClick={exportStory} size="sm" variant="outline">
                <Download className="w-4 h-4 mr-2" />
                Export
              </Button>
            </div>
          </CardHeader>
          <CardContent>
            <div className="prose dark:prose-invert max-w-none">
              <h2>{generatedStory.companyName}</h2>
              <p className="text-sm text-slate-500 dark:text-slate-400">
                {generatedStory.industry}
              </p>
              <h3>The Challenge</h3>
              <p>{generatedStory.challenge}</p>
              <h3>The Solution</h3>
              <p>{generatedStory.solution}</p>
              <h3>Results</h3>
              <p>{generatedStory.results}</p>
              <div className="bg-slate-50 dark:bg-slate-800 rounded-lg p-4 my-4">
                <h4 className="font-semibold mb-2">Key Metrics</h4>
                <ul>
                  <li>Time Saved: {generatedStory.metrics.timeSaved}</li>
                  <li>Accuracy: {generatedStory.metrics.accuracy}</li>
                  <li>Cost Savings: {generatedStory.metrics.costSavings}</li>
                </ul>
              </div>
              <blockquote className="border-l-4 border-blue-500 pl-4 italic">
                {generatedStory.quote}
              </blockquote>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
