/**
 * RFC 7807 / RFC 9457 Problem Details for HTTP APIs
 *
 * Standardized, machine-readable error envelope for Astra and Settler API surfaces.
 */

export interface InvalidParameter {
  name: string;
  reason: string;
  value?: unknown;
}

export interface ProblemDetails {
  /** A URI reference that identifies the problem type */
  type: string;
  /** A short, human-readable summary of the problem type */
  title: string;
  /** The HTTP status code generated by the origin server for this occurrence */
  status: number;
  /** A human-readable explanation specific to this occurrence of the problem */
  detail: string;
  /** A URI reference that identifies the specific occurrence of the problem */
  instance: string;
  /** Error classification code */
  code: string;
  /** Multi-tenant partition context */
  tenantId: string;
  /** Distributed request trace identifier */
  traceId: string;
  /** ISO timestamp of occurrence */
  timestamp: string;
  /** Parameter validation errors (if applicable) */
  invalidParams?: InvalidParameter[];
  /** Cryptographic proof context (if applicable) */
  merkleRoot?: string;
}

export function createProblemDetails(options: {
  type?: string;
  title: string;
  status: number;
  detail: string;
  instance?: string;
  code: string;
  tenantId: string;
  traceId?: string;
  invalidParams?: InvalidParameter[];
  merkleRoot?: string;
}): ProblemDetails {
  return {
    type: options.type ?? `https://api.settler.io/errors/${options.code.toLowerCase()}`,
    title: options.title,
    status: options.status,
    detail: options.detail,
    instance: options.instance ?? `/v1/requests/${options.traceId ?? "anon"}`,
    code: options.code,
    tenantId: options.tenantId,
    traceId: options.traceId ?? `trace_${Date.now()}`,
    timestamp: new Date().toISOString(),
    invalidParams: options.invalidParams,
    merkleRoot: options.merkleRoot,
  };
}
