import { Metadata } from "next";
import Link from "next/link";
import {
  ArrowRight,
  CheckCircle2,
  ClipboardList,
  FileCheck,
  HeadphonesIcon,
  BarChart3,
  Shield,
  Users,
  Calendar,
} from "lucide-react";
import { Navigation } from "@/components/Navigation";
import { Footer } from "@/components/Footer";
import { PageHero, Section, SectionHeader } from "@/components/site/primitives";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { UiLink } from "@/components/ui/link";

export const metadata: Metadata = {
  title: "Managed Reconciliation Operations — Settler",
  description:
    "Settler Managed Operations delivers operator-assisted reconciliation: onboarding, exception triage, monthly close preparation, and audit packet delivery for teams that need results without hiring a reconciliation engineer.",
};

const serviceDeliverables = [
  {
    icon: ClipboardList,
    title: "Onboarding and configuration",
    description:
      "We scope your reconciliation requirements, configure your adapters, define your matching rules, and run your first production reconciliation — no guesswork, no ramp-up period.",
    included: [
      "Adapter setup (Stripe, bank, ERP, or custom)",
      "Matching rule configuration and tolerance review",
      "First production run with results walkthrough",
      "Runbook handoff for your team",
    ],
  },
  {
    icon: HeadphonesIcon,
    title: "Ongoing exception triage",
    description:
      "Named operator attention on your exception queue. We review open exceptions, apply resolution patterns, and escalate only what genuinely needs your decision — reducing review burden without removing authority.",
    included: [
      "Weekly exception queue review",
      "Pattern classification and resolution recommendations",
      "Escalation with evidence context where needed",
      "Exception audit trail for your records",
    ],
  },
  {
    icon: Calendar,
    title: "Monthly close support",
    description:
      "Reconciliation-aligned close operations delivered on your schedule. We prepare the close run, review open items, and produce a summary ready for your finance team or auditors.",
    included: [
      "Pre-close data quality check",
      "Close run execution and review",
      "Open exception summary with operator notes",
      "Delivered by your agreed close date",
    ],
  },
  {
    icon: FileCheck,
    title: "Audit evidence packets",
    description:
      "When auditors, compliance teams, or counterparties request reconciliation evidence, we prepare structured audit packets: run summaries, exception disposition logs, proofpack artifacts, and methodology notes.",
    included: [
      "Run summary with result counts and posture",
      "Exception disposition log with resolution rationale",
      "Proofpack artifact (hash-linked evidence JSON)",
      "Methodology notes for auditor review",
    ],
  },
  {
    icon: BarChart3,
    title: "Performance and trend reporting",
    description:
      "Monthly operational summary covering match rate trends, exception patterns, recurring families, and any configuration changes. Delivered as a structured report.",
    included: [
      "Match rate and exception density trends",
      "Recurring exception family tracking",
      "Configuration change log",
      "Operator notes and recommendations",
    ],
  },
];

const operationalBoundaries = [
  "We configure and operate Settler on your behalf — you retain full access to the console at all times.",
  "You remain the final authority on exception resolution. We recommend, you decide.",
  "All operator actions are logged in the audit trail. Nothing happens without a record.",
  "Your data stays in your tenant. Operator access is scoped and revocable.",
  "SLAs for exception review cadence and close support are agreed at engagement start.",
];

const whyManaged = [
  {
    title: "No reconciliation engineer needed",
    description:
      "Skip the 3–6 month ramp to hire and onboard a reconciliation specialist. Get operational results from the first week.",
  },
  {
    title: "Consistent close quality",
    description:
      "Monthly close support delivered on your schedule by operators who know the system — not a last-minute scramble.",
  },
  {
    title: "Audit-ready evidence without manual assembly",
    description:
      "Structured audit packets prepared when you need them, using the evidence already generated by every reconciliation run.",
  },
  {
    title: "Clear escalation path",
    description:
      "Exceptions that need human judgment get escalated with context. You never get a question without supporting evidence.",
  },
];

export default function ManagedOperationsPage() {
  return (
    <div className="min-h-screen bg-background">
      <Navigation />
      <main id="main-content" className="pt-16">
        <PageHero
          eyebrow="Managed Operations"
          title="Reconciliation operations, delivered."
          description="Settler Managed Operations pairs the platform with named operator attention. Onboarding, triage, monthly close, and audit packets — without building an in-house reconciliation function."
          actions={
            <>
              <Button asChild size="lg">
                <UiLink href="/contact">
                  Discuss your requirements <ArrowRight className="ml-2 h-4 w-4" />
                </UiLink>
              </Button>
              <Button variant="outline" asChild size="lg">
                <UiLink href="/pricing">See pricing</UiLink>
              </Button>
            </>
          }
        />

        {/* Who this is for */}
        <Section className="py-16 border-t border-border/40">
          <SectionHeader
            title="Who this is for"
            description="Managed Operations is designed for teams that need reconciliation results but are not ready to staff or manage a dedicated reconciliation function."
          />
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-8">
            {[
              {
                title: "Finance teams scaling past spreadsheets",
                description:
                  "You need deterministic reconciliation and clean exception audit trails — but your team is already at capacity.",
              },
              {
                title: "Operators without a dedicated recon engineer",
                description:
                  "You have volume and complexity but the budget or timeline for a specialist hire doesn't match the urgency.",
              },
              {
                title: "Teams approaching an audit or compliance review",
                description:
                  "You need structured evidence and reconciliation history prepared for external reviewers on a defined timeline.",
              },
            ].map((item) => (
              <Card key={item.title} className="border-border/60">
                <CardHeader className="pb-2">
                  <CardTitle className="text-base font-semibold">{item.title}</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-muted-foreground leading-relaxed">{item.description}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </Section>

        {/* Service deliverables */}
        <Section className="py-16 bg-muted/10 border-y border-border/40">
          <SectionHeader
            title="What's included"
            description="Each managed engagement covers a defined set of deliverables. Scope is agreed at engagement start — no undefined commitments."
          />
          <div className="mt-10 space-y-6">
            {serviceDeliverables.map((item) => {
              const Icon = item.icon;
              return (
                <Card key={item.title} className="border-border/60">
                  <CardContent className="pt-6">
                    <div className="grid grid-cols-1 lg:grid-cols-[2fr_3fr] gap-8">
                      <div className="space-y-3">
                        <div className="flex items-center gap-3">
                          <div className="p-2 rounded-lg bg-primary/10 text-primary">
                            <Icon className="h-5 w-5" />
                          </div>
                          <h3 className="font-semibold text-foreground">{item.title}</h3>
                        </div>
                        <p className="text-sm text-muted-foreground leading-relaxed">
                          {item.description}
                        </p>
                      </div>
                      <ul className="space-y-2">
                        {item.included.map((point) => (
                          <li key={point} className="flex items-start gap-2 text-sm">
                            <CheckCircle2 className="h-4 w-4 text-primary mt-0.5 flex-shrink-0" />
                            <span className="text-muted-foreground">{point}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  </CardContent>
                </Card>
              );
            })}
          </div>
        </Section>

        {/* Why managed */}
        <Section className="py-16">
          <SectionHeader
            title="Why choose managed operations"
            description="Specific operational advantages over self-service or ad-hoc reconciliation."
          />
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-8">
            {whyManaged.map((item) => (
              <div key={item.title} className="space-y-2 p-6 rounded-xl border border-border/60 bg-card/40">
                <h3 className="font-semibold text-sm text-foreground">{item.title}</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">{item.description}</p>
              </div>
            ))}
          </div>
        </Section>

        {/* Operational boundaries */}
        <Section className="py-16 bg-muted/10 border-y border-border/40">
          <div className="max-w-3xl mx-auto">
            <div className="flex items-center gap-3 mb-6">
              <Shield className="h-5 w-5 text-primary" />
              <h2 className="text-xl font-bold">How it works: what we do and what you control</h2>
            </div>
            <p className="text-muted-foreground text-sm mb-6 leading-relaxed">
              Managed Operations is not a black box. You retain full console access, full audit trail
              visibility, and final authority over every exception resolution. Here is what the
              engagement model means in practice:
            </p>
            <ul className="space-y-3">
              {operationalBoundaries.map((boundary) => (
                <li key={boundary} className="flex items-start gap-3 text-sm">
                  <CheckCircle2 className="h-4 w-4 text-primary mt-0.5 flex-shrink-0" />
                  <span className="text-foreground">{boundary}</span>
                </li>
              ))}
            </ul>
          </div>
        </Section>

        {/* Engagement model */}
        <Section className="py-16">
          <div className="max-w-4xl mx-auto">
            <SectionHeader
              title="Engagement model"
              description="Managed Operations engagements are month-to-month with a defined scope agreed at start. Pricing is based on volume, cadence, and adapter complexity."
            />
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-10">
              {[
                {
                  step: "1",
                  title: "Scoping call",
                  description:
                    "30-minute conversation to understand your data sources, volume, close schedule, and any pending audit requirements.",
                },
                {
                  step: "2",
                  title: "Proposal and setup",
                  description:
                    "We send a written scope with deliverables, SLAs, and pricing. On acceptance, we begin adapter configuration and onboarding within 5 business days.",
                },
                {
                  step: "3",
                  title: "Ongoing operations",
                  description:
                    "Regular exception triage, close support on your schedule, and audit packets on request. Monthly review call to discuss trends and any configuration updates.",
                },
              ].map((item) => (
                <div key={item.step} className="space-y-3">
                  <div className="flex items-center gap-3">
                    <Badge variant="outline" className="h-7 w-7 rounded-full flex items-center justify-center text-sm font-bold">
                      {item.step}
                    </Badge>
                    <h3 className="font-semibold text-sm">{item.title}</h3>
                  </div>
                  <p className="text-sm text-muted-foreground leading-relaxed pl-10">
                    {item.description}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </Section>

        {/* CTA */}
        <Section className="py-20 bg-muted/10 border-t border-border/40">
          <div className="max-w-2xl mx-auto text-center space-y-6">
            <div className="flex items-center justify-center gap-2 text-muted-foreground">
              <Users className="h-4 w-4" />
              <span className="text-xs font-semibold uppercase tracking-[0.2em]">
                Ready to discuss managed operations
              </span>
            </div>
            <h2 className="text-3xl font-bold tracking-tight">
              Start with a scoping conversation.
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              No commitment required. We'll scope your requirements, answer technical questions, and
              give you a clear picture of what managed operations would look like for your team.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center pt-2">
              <Button asChild size="lg">
                <Link href="/contact">
                  Schedule a scoping call <ArrowRight className="ml-2 h-4 w-4" />
                </Link>
              </Button>
              <Button variant="outline" asChild size="lg">
                <Link href="/pricing">View pricing tiers</Link>
              </Button>
            </div>
          </div>
        </Section>
      </main>
      <Footer />
    </div>
  );
}
