-- Consolidate multiple permissive RLS policies (2026-10-03).
-- Generated by tools in the operator scratch space; equivalence
-- manifest records each (table, action, role) cell's before/after
-- predicate. All policies on these tables are PERMISSIVE (OR
-- semantics), so disjunctive merging preserves visibility exactly.

-- =============== add_on_purchases ===============
CREATE POLICY "merged_add_on_purchases_select" ON public.add_on_purchases AS PERMISSIVE FOR SELECT TO authenticated
  USING ((((billing_account_id IN ( SELECT billing_accounts.id
   FROM billing_accounts
  WHERE (billing_accounts.user_id = ( SELECT auth.uid() AS uid))))) OR ((EXISTS ( SELECT 1
   FROM billing_accounts ba
  WHERE ((ba.id = add_on_purchases.billing_account_id) AND ((ba.user_id = ( SELECT auth.uid() AS uid)) OR (ba.tenant_id IN ( SELECT tenant_users.tenant_id
           FROM tenant_users
          WHERE (tenant_users.user_id = ( SELECT auth.uid() AS uid)))))))))))
;
CREATE POLICY "merged_add_on_purchases_insert" ON public.add_on_purchases AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((((EXISTS ( SELECT 1
   FROM billing_accounts ba
  WHERE ((ba.id = add_on_purchases.billing_account_id) AND ((ba.user_id = ( SELECT auth.uid() AS uid)) OR (ba.tenant_id IN ( SELECT tenant_users.tenant_id
           FROM tenant_users
          WHERE (tenant_users.user_id = ( SELECT auth.uid() AS uid))))))))) OR ((billing_account_id IN ( SELECT billing_accounts.id
   FROM billing_accounts
  WHERE (billing_accounts.user_id = ( SELECT auth.uid() AS uid)))))))
;
CREATE POLICY "merged_add_on_purchases_update" ON public.add_on_purchases AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((((billing_account_id IN ( SELECT billing_accounts.id
   FROM billing_accounts
  WHERE (billing_accounts.user_id = ( SELECT auth.uid() AS uid))))) OR ((EXISTS ( SELECT 1
   FROM billing_accounts ba
  WHERE ((ba.id = add_on_purchases.billing_account_id) AND ((ba.user_id = ( SELECT auth.uid() AS uid)) OR (ba.tenant_id IN ( SELECT tenant_users.tenant_id
           FROM tenant_users
          WHERE (tenant_users.user_id = ( SELECT auth.uid() AS uid)))))))))))
  WITH CHECK ((((billing_account_id IN ( SELECT billing_accounts.id
   FROM billing_accounts
  WHERE (billing_accounts.user_id = ( SELECT auth.uid() AS uid))))) OR ((EXISTS ( SELECT 1
   FROM billing_accounts ba
  WHERE ((ba.id = add_on_purchases.billing_account_id) AND ((ba.user_id = ( SELECT auth.uid() AS uid)) OR (ba.tenant_id IN ( SELECT tenant_users.tenant_id
           FROM tenant_users
          WHERE (tenant_users.user_id = ( SELECT auth.uid() AS uid)))))))))))
;
CREATE POLICY "merged_add_on_purchases_delete" ON public.add_on_purchases AS PERMISSIVE FOR DELETE TO authenticated
  USING ((((EXISTS ( SELECT 1
   FROM billing_accounts ba
  WHERE ((ba.id = add_on_purchases.billing_account_id) AND ((ba.user_id = ( SELECT auth.uid() AS uid)) OR (ba.tenant_id IN ( SELECT tenant_users.tenant_id
           FROM tenant_users
          WHERE (tenant_users.user_id = ( SELECT auth.uid() AS uid))))))))) OR ((billing_account_id IN ( SELECT billing_accounts.id
   FROM billing_accounts
  WHERE (billing_accounts.user_id = ( SELECT auth.uid() AS uid)))))))
;
DROP POLICY IF EXISTS "add_on_purchases_delete_authenticated" ON public.add_on_purchases;
DROP POLICY IF EXISTS "add_on_purchases_insert_authenticated" ON public.add_on_purchases;
DROP POLICY IF EXISTS "add_on_purchases_isolation" ON public.add_on_purchases;
DROP POLICY IF EXISTS "add_on_purchases_select_authenticated" ON public.add_on_purchases;
DROP POLICY IF EXISTS "add_on_purchases_update_authenticated" ON public.add_on_purchases;
-- =============== add_ons ===============
CREATE POLICY "merged_add_ons_select" ON public.add_ons AS PERMISSIVE FOR SELECT TO public
  USING (((((is_active = true)) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR (((is_active = true) OR (EXISTS ( SELECT 1
   FROM add_on_purchases
  WHERE ((add_on_purchases.add_on_id = add_ons.id) AND (EXISTS ( SELECT 1
           FROM billing_accounts
          WHERE ((billing_accounts.id = add_on_purchases.billing_account_id) AND (billing_accounts.user_id = current_user_id())))))))))))
;
CREATE POLICY "merged_add_ons_insert" ON public.add_ons AS PERMISSIVE FOR INSERT TO public
  WITH CHECK ((false))
;
CREATE POLICY "merged_add_ons_update" ON public.add_ons AS PERMISSIVE FOR UPDATE TO public
  USING ((false))
  WITH CHECK ((false))
;
CREATE POLICY "merged_add_ons_delete" ON public.add_ons AS PERMISSIVE FOR DELETE TO public
  USING ((false))
;
DROP POLICY IF EXISTS "add_ons_delete_admin" ON public.add_ons;
DROP POLICY IF EXISTS "add_ons_insert_admin" ON public.add_ons;
DROP POLICY IF EXISTS "add_ons_select" ON public.add_ons;
DROP POLICY IF EXISTS "add_ons_select_public" ON public.add_ons;
DROP POLICY IF EXISTS "add_ons_update_admin" ON public.add_ons;
-- =============== audit_logs ===============
CREATE POLICY "merged_audit_logs_select" ON public.audit_logs AS PERMISSIVE FOR SELECT TO authenticated
  USING (((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids)) OR (user_id = ( SELECT auth.uid() AS uid)))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
CREATE POLICY "merged_audit_logs_insert" ON public.audit_logs AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK (((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))))
;
CREATE POLICY "merged_audit_logs_update" ON public.audit_logs AS PERMISSIVE FOR UPDATE TO authenticated
  USING (((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))))
  WITH CHECK (((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))))
;
CREATE POLICY "merged_audit_logs_delete" ON public.audit_logs AS PERMISSIVE FOR DELETE TO authenticated
  USING (((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))))
;
DROP POLICY IF EXISTS "audit_logs_select_tenant" ON public.audit_logs;
DROP POLICY IF EXISTS "tenant_delete" ON public.audit_logs;
DROP POLICY IF EXISTS "tenant_insert" ON public.audit_logs;
DROP POLICY IF EXISTS "tenant_select" ON public.audit_logs;
DROP POLICY IF EXISTS "tenant_update" ON public.audit_logs;
-- =============== billing_accounts ===============
CREATE POLICY "merged_billing_accounts_select" ON public.billing_accounts AS PERMISSIVE FOR SELECT TO public
  USING ((((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER'))) OR ((((user_id = ( SELECT auth.uid() AS uid)) OR (tenant_id IN ( SELECT tu.tenant_id
   FROM tenant_users tu
  WHERE (tu.user_id = ( SELECT auth.uid() AS uid)))) OR (tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR (((user_id = ( SELECT auth.uid() AS uid))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER')))))
;
CREATE POLICY "merged_billing_accounts_insert" ON public.billing_accounts AS PERMISSIVE FOR INSERT TO public
  WITH CHECK ((((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER'))) OR (((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER')))))
;
CREATE POLICY "merged_billing_accounts_update" ON public.billing_accounts AS PERMISSIVE FOR UPDATE TO public
  USING ((((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER'))) OR ((((user_id = ( SELECT auth.uid() AS uid)) OR (tenant_id IN ( SELECT tenant_users.tenant_id
   FROM tenant_users
  WHERE (tenant_users.user_id = ( SELECT auth.uid() AS uid)))) OR (tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR (((user_id = ( SELECT auth.uid() AS uid))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER')))))
  WITH CHECK ((((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER'))) OR ((((user_id = ( SELECT auth.uid() AS uid)) OR (tenant_id IN ( SELECT tenant_users.tenant_id
   FROM tenant_users
  WHERE (tenant_users.user_id = ( SELECT auth.uid() AS uid)))) OR (tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR (((user_id = ( SELECT auth.uid() AS uid))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER')))))
;
CREATE POLICY "merged_billing_accounts_delete" ON public.billing_accounts AS PERMISSIVE FOR DELETE TO public
  USING ((((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER'))) OR (((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER')))))
;
DROP POLICY IF EXISTS "Service role can manage billing accounts" ON public.billing_accounts;
DROP POLICY IF EXISTS "billing_accounts_select_authenticated_combined" ON public.billing_accounts;
DROP POLICY IF EXISTS "billing_accounts_select_own" ON public.billing_accounts;
DROP POLICY IF EXISTS "billing_accounts_update_authenticated" ON public.billing_accounts;
DROP POLICY IF EXISTS "billing_accounts_update_own" ON public.billing_accounts;
DROP POLICY IF EXISTS "tenant_delete" ON public.billing_accounts;
DROP POLICY IF EXISTS "tenant_insert" ON public.billing_accounts;
-- =============== contract_versions ===============
CREATE POLICY "merged_contract_versions_select" ON public.contract_versions AS PERMISSIVE FOR SELECT TO authenticated
  USING ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
CREATE POLICY "merged_contract_versions_insert" ON public.contract_versions AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
CREATE POLICY "merged_contract_versions_update" ON public.contract_versions AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
  WITH CHECK ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
CREATE POLICY "merged_contract_versions_delete" ON public.contract_versions AS PERMISSIVE FOR DELETE TO authenticated
  USING ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
DROP POLICY IF EXISTS "contract_versions_delete" ON public.contract_versions;
DROP POLICY IF EXISTS "contract_versions_insert" ON public.contract_versions;
DROP POLICY IF EXISTS "contract_versions_select" ON public.contract_versions;
DROP POLICY IF EXISTS "contract_versions_update" ON public.contract_versions;
DROP POLICY IF EXISTS "tenant_delete" ON public.contract_versions;
DROP POLICY IF EXISTS "tenant_insert" ON public.contract_versions;
DROP POLICY IF EXISTS "tenant_select" ON public.contract_versions;
DROP POLICY IF EXISTS "tenant_update" ON public.contract_versions;
-- =============== drift_events ===============
CREATE POLICY "merged_drift_events_select" ON public.drift_events AS PERMISSIVE FOR SELECT TO authenticated
  USING ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
CREATE POLICY "merged_drift_events_insert" ON public.drift_events AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
CREATE POLICY "merged_drift_events_update" ON public.drift_events AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
  WITH CHECK ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
CREATE POLICY "merged_drift_events_delete" ON public.drift_events AS PERMISSIVE FOR DELETE TO authenticated
  USING ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
DROP POLICY IF EXISTS "drift_events_isolation" ON public.drift_events;
DROP POLICY IF EXISTS "tenant_delete" ON public.drift_events;
DROP POLICY IF EXISTS "tenant_insert" ON public.drift_events;
DROP POLICY IF EXISTS "tenant_select" ON public.drift_events;
DROP POLICY IF EXISTS "tenant_update" ON public.drift_events;
-- =============== exports ===============
CREATE POLICY "merged_exports_select" ON public.exports AS PERMISSIVE FOR SELECT TO authenticated
  USING ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
CREATE POLICY "merged_exports_insert" ON public.exports AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
CREATE POLICY "merged_exports_update" ON public.exports AS PERMISSIVE FOR UPDATE TO authenticated
  USING (((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))))
  WITH CHECK (((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))))
;
CREATE POLICY "merged_exports_delete" ON public.exports AS PERMISSIVE FOR DELETE TO authenticated
  USING (((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))))
;
DROP POLICY IF EXISTS "exports_insert" ON public.exports;
DROP POLICY IF EXISTS "exports_select" ON public.exports;
DROP POLICY IF EXISTS "tenant_delete" ON public.exports;
DROP POLICY IF EXISTS "tenant_insert" ON public.exports;
DROP POLICY IF EXISTS "tenant_select" ON public.exports;
DROP POLICY IF EXISTS "tenant_update" ON public.exports;
-- =============== feature_flag_overrides ===============
CREATE POLICY "merged_feature_flag_overrides_select" ON public.feature_flag_overrides AS PERMISSIVE FOR SELECT TO authenticated
  USING ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
CREATE POLICY "merged_feature_flag_overrides_insert" ON public.feature_flag_overrides AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
CREATE POLICY "merged_feature_flag_overrides_update" ON public.feature_flag_overrides AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
  WITH CHECK ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
CREATE POLICY "merged_feature_flag_overrides_delete" ON public.feature_flag_overrides AS PERMISSIVE FOR DELETE TO authenticated
  USING ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
DROP POLICY IF EXISTS "feature_flag_overrides_isolation" ON public.feature_flag_overrides;
DROP POLICY IF EXISTS "tenant_delete" ON public.feature_flag_overrides;
DROP POLICY IF EXISTS "tenant_insert" ON public.feature_flag_overrides;
DROP POLICY IF EXISTS "tenant_select" ON public.feature_flag_overrides;
DROP POLICY IF EXISTS "tenant_update" ON public.feature_flag_overrides;
-- =============== feature_flags ===============
CREATE POLICY "merged_feature_flags_select" ON public.feature_flags AS PERMISSIVE FOR SELECT TO authenticated
  USING (((((is_global = true) OR (billing_account_id IN ( SELECT billing_accounts.id
   FROM billing_accounts
  WHERE (billing_accounts.user_id = ( SELECT auth.uid() AS uid)))))) OR ((billing_account_id IN ( SELECT ba.id
   FROM billing_accounts ba
  WHERE ((ba.user_id = ( SELECT auth.uid() AS uid)) AND ((ba.status)::text = 'active'::text) AND (ba.deleted_at IS NULL)))))))
;
CREATE POLICY "merged_feature_flags_insert" ON public.feature_flags AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((((billing_account_id IN ( SELECT ba.id
   FROM billing_accounts ba
  WHERE ((ba.user_id = ( SELECT auth.uid() AS uid)) AND ((ba.status)::text = 'active'::text) AND (ba.deleted_at IS NULL)))) AND has_active_subscription(( SELECT auth.uid() AS uid)))))
;
CREATE POLICY "merged_feature_flags_update" ON public.feature_flags AS PERMISSIVE FOR UPDATE TO authenticated
  USING (((billing_account_id IN ( SELECT ba.id
   FROM billing_accounts ba
  WHERE ((ba.user_id = ( SELECT auth.uid() AS uid)) AND ((ba.status)::text = 'active'::text) AND (ba.deleted_at IS NULL))))))
  WITH CHECK (((billing_account_id IN ( SELECT ba.id
   FROM billing_accounts ba
  WHERE ((ba.user_id = ( SELECT auth.uid() AS uid)) AND ((ba.status)::text = 'active'::text) AND (ba.deleted_at IS NULL))))))
;
CREATE POLICY "merged_feature_flags_delete" ON public.feature_flags AS PERMISSIVE FOR DELETE TO authenticated
  USING (((billing_account_id IN ( SELECT ba.id
   FROM billing_accounts ba
  WHERE ((ba.user_id = ( SELECT auth.uid() AS uid)) AND ((ba.status)::text = 'active'::text) AND (ba.deleted_at IS NULL))))))
;
DROP POLICY IF EXISTS "feature_flags_select" ON public.feature_flags;
DROP POLICY IF EXISTS "tenant_isolation_delete" ON public.feature_flags;
DROP POLICY IF EXISTS "tenant_isolation_insert" ON public.feature_flags;
DROP POLICY IF EXISTS "tenant_isolation_select" ON public.feature_flags;
DROP POLICY IF EXISTS "tenant_isolation_update" ON public.feature_flags;
-- =============== idempotency_keys ===============
CREATE POLICY "merged_idempotency_keys_select" ON public.idempotency_keys AS PERMISSIVE FOR SELECT TO public
  USING ((((CURRENT_USER = 'service_role'::name)) OR ((tenant_id = (( SELECT current_setting('app.current_tenant_id'::text, true) AS current_setting))::uuid)) OR (((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER')))))
;
CREATE POLICY "merged_idempotency_keys_insert" ON public.idempotency_keys AS PERMISSIVE FOR INSERT TO public
  WITH CHECK ((((CURRENT_USER = 'service_role'::name)) OR (((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR ((tenant_id = (( SELECT current_setting('app.current_tenant_id'::text, true) AS current_setting))::uuid))))
;
CREATE POLICY "merged_idempotency_keys_update" ON public.idempotency_keys AS PERMISSIVE FOR UPDATE TO public
  USING ((((CURRENT_USER = 'service_role'::name)) OR ((tenant_id = (( SELECT current_setting('app.current_tenant_id'::text, true) AS current_setting))::uuid)) OR (((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER')))))
  WITH CHECK ((((CURRENT_USER = 'service_role'::name)) OR ((tenant_id = (( SELECT current_setting('app.current_tenant_id'::text, true) AS current_setting))::uuid)) OR (((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER')))))
;
CREATE POLICY "merged_idempotency_keys_delete" ON public.idempotency_keys AS PERMISSIVE FOR DELETE TO public
  USING ((((CURRENT_USER = 'service_role'::name)) OR (((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR ((tenant_id = (( SELECT current_setting('app.current_tenant_id'::text, true) AS current_setting))::uuid))))
;
DROP POLICY IF EXISTS "service_role_bypass_idempotency" ON public.idempotency_keys;
DROP POLICY IF EXISTS "tenant_delete" ON public.idempotency_keys;
DROP POLICY IF EXISTS "tenant_insert" ON public.idempotency_keys;
DROP POLICY IF EXISTS "tenant_isolation_idempotency_keys" ON public.idempotency_keys;
DROP POLICY IF EXISTS "tenant_select" ON public.idempotency_keys;
DROP POLICY IF EXISTS "tenant_update" ON public.idempotency_keys;
-- =============== ingestion_dlq ===============
CREATE POLICY "merged_ingestion_dlq_select" ON public.ingestion_dlq AS PERMISSIVE FOR SELECT TO public
  USING ((((CURRENT_USER = 'service_role'::name)) OR (((tenant_id = (( SELECT current_setting('app.current_tenant_id'::text, true) AS current_setting))::uuid) OR (tenant_id IS NULL)))))
;
CREATE POLICY "merged_ingestion_dlq_insert" ON public.ingestion_dlq AS PERMISSIVE FOR INSERT TO public
  WITH CHECK ((((CURRENT_USER = 'service_role'::name)) OR (((tenant_id = (( SELECT current_setting('app.current_tenant_id'::text, true) AS current_setting))::uuid) OR (tenant_id IS NULL)))))
;
CREATE POLICY "merged_ingestion_dlq_update" ON public.ingestion_dlq AS PERMISSIVE FOR UPDATE TO public
  USING ((((CURRENT_USER = 'service_role'::name)) OR (((tenant_id = (( SELECT current_setting('app.current_tenant_id'::text, true) AS current_setting))::uuid) OR (tenant_id IS NULL)))))
  WITH CHECK ((((CURRENT_USER = 'service_role'::name)) OR (((tenant_id = (( SELECT current_setting('app.current_tenant_id'::text, true) AS current_setting))::uuid) OR (tenant_id IS NULL)))))
;
CREATE POLICY "merged_ingestion_dlq_delete" ON public.ingestion_dlq AS PERMISSIVE FOR DELETE TO public
  USING ((((CURRENT_USER = 'service_role'::name)) OR (((tenant_id = (( SELECT current_setting('app.current_tenant_id'::text, true) AS current_setting))::uuid) OR (tenant_id IS NULL)))))
;
DROP POLICY IF EXISTS "service_role_bypass_dlq" ON public.ingestion_dlq;
DROP POLICY IF EXISTS "tenant_isolation_ingestion_dlq" ON public.ingestion_dlq;
-- =============== ingestion_sources ===============
CREATE POLICY "merged_ingestion_sources_select" ON public.ingestion_sources AS PERMISSIVE FOR SELECT TO authenticated
  USING ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
CREATE POLICY "merged_ingestion_sources_insert" ON public.ingestion_sources AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
CREATE POLICY "merged_ingestion_sources_update" ON public.ingestion_sources AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
  WITH CHECK ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
CREATE POLICY "merged_ingestion_sources_delete" ON public.ingestion_sources AS PERMISSIVE FOR DELETE TO authenticated
  USING (((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))))
;
DROP POLICY IF EXISTS "ingestion_sources_insert" ON public.ingestion_sources;
DROP POLICY IF EXISTS "ingestion_sources_select" ON public.ingestion_sources;
DROP POLICY IF EXISTS "ingestion_sources_update" ON public.ingestion_sources;
DROP POLICY IF EXISTS "tenant_delete" ON public.ingestion_sources;
DROP POLICY IF EXISTS "tenant_insert" ON public.ingestion_sources;
DROP POLICY IF EXISTS "tenant_select" ON public.ingestion_sources;
DROP POLICY IF EXISTS "tenant_update" ON public.ingestion_sources;
-- =============== ingestions ===============
CREATE POLICY "merged_ingestions_select" ON public.ingestions AS PERMISSIVE FOR SELECT TO authenticated
  USING ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
CREATE POLICY "merged_ingestions_insert" ON public.ingestions AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
CREATE POLICY "merged_ingestions_update" ON public.ingestions AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
  WITH CHECK ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
CREATE POLICY "merged_ingestions_delete" ON public.ingestions AS PERMISSIVE FOR DELETE TO authenticated
  USING ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
DROP POLICY IF EXISTS "ingestions_isolation" ON public.ingestions;
DROP POLICY IF EXISTS "tenant_delete" ON public.ingestions;
DROP POLICY IF EXISTS "tenant_insert" ON public.ingestions;
DROP POLICY IF EXISTS "tenant_select" ON public.ingestions;
DROP POLICY IF EXISTS "tenant_update" ON public.ingestions;
-- =============== mapping_templates ===============
CREATE POLICY "merged_mapping_templates_select" ON public.mapping_templates AS PERMISSIVE FOR SELECT TO authenticated
  USING (((((is_public = true) OR (is_system = true) OR (tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids)))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
CREATE POLICY "merged_mapping_templates_insert" ON public.mapping_templates AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
CREATE POLICY "merged_mapping_templates_update" ON public.mapping_templates AS PERMISSIVE FOR UPDATE TO authenticated
  USING (((((is_system = false) AND (tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids)))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
  WITH CHECK (((((is_system = false) AND (tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids)))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
CREATE POLICY "merged_mapping_templates_delete" ON public.mapping_templates AS PERMISSIVE FOR DELETE TO authenticated
  USING (((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))))
;
DROP POLICY IF EXISTS "mapping_templates_insert" ON public.mapping_templates;
DROP POLICY IF EXISTS "mapping_templates_select" ON public.mapping_templates;
DROP POLICY IF EXISTS "mapping_templates_update" ON public.mapping_templates;
DROP POLICY IF EXISTS "tenant_delete" ON public.mapping_templates;
DROP POLICY IF EXISTS "tenant_insert" ON public.mapping_templates;
DROP POLICY IF EXISTS "tenant_select" ON public.mapping_templates;
DROP POLICY IF EXISTS "tenant_update" ON public.mapping_templates;
-- =============== memberships ===============
CREATE POLICY "merged_memberships_select" ON public.memberships AS PERMISSIVE FOR SELECT TO public
  USING ((((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER'))) OR (((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR (((user_id = ( SELECT auth.uid() AS uid))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER')))))
;
CREATE POLICY "merged_memberships_insert" ON public.memberships AS PERMISSIVE FOR INSERT TO public
  WITH CHECK (((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR (((user_id = ( SELECT auth.uid() AS uid))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR ((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER')))))
;
CREATE POLICY "merged_memberships_update" ON public.memberships AS PERMISSIVE FOR UPDATE TO public
  USING ((((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER'))) OR (((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR (((user_id = ( SELECT auth.uid() AS uid))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER')))))
  WITH CHECK ((((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER'))) OR (((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR (((user_id = ( SELECT auth.uid() AS uid))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER')))))
;
CREATE POLICY "merged_memberships_delete" ON public.memberships AS PERMISSIVE FOR DELETE TO public
  USING (((((user_id = ( SELECT auth.uid() AS uid))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR ((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER')))))
;
DROP POLICY IF EXISTS "memberships_delete_owned" ON public.memberships;
DROP POLICY IF EXISTS "memberships_insert" ON public.memberships;
DROP POLICY IF EXISTS "memberships_insert_owned" ON public.memberships;
DROP POLICY IF EXISTS "memberships_modify_service" ON public.memberships;
DROP POLICY IF EXISTS "memberships_select" ON public.memberships;
DROP POLICY IF EXISTS "memberships_select_own" ON public.memberships;
DROP POLICY IF EXISTS "memberships_update" ON public.memberships;
DROP POLICY IF EXISTS "memberships_update_owned" ON public.memberships;
-- =============== normalized_transactions ===============
CREATE POLICY "merged_normalized_transactions_select" ON public.normalized_transactions AS PERMISSIVE FOR SELECT TO authenticated
  USING ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
CREATE POLICY "merged_normalized_transactions_insert" ON public.normalized_transactions AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
CREATE POLICY "merged_normalized_transactions_update" ON public.normalized_transactions AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
  WITH CHECK ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
CREATE POLICY "merged_normalized_transactions_delete" ON public.normalized_transactions AS PERMISSIVE FOR DELETE TO authenticated
  USING ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
DROP POLICY IF EXISTS "normalized_transactions_isolation" ON public.normalized_transactions;
DROP POLICY IF EXISTS "tenant_delete" ON public.normalized_transactions;
DROP POLICY IF EXISTS "tenant_insert" ON public.normalized_transactions;
DROP POLICY IF EXISTS "tenant_select" ON public.normalized_transactions;
DROP POLICY IF EXISTS "tenant_update" ON public.normalized_transactions;
-- =============== raw_records ===============
CREATE POLICY "merged_raw_records_select" ON public.raw_records AS PERMISSIVE FOR SELECT TO public
  USING (((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR ((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER'))) OR (((tenant_id IN ( SELECT ba.tenant_id
   FROM billing_accounts ba
  WHERE ((ba.user_id = ( SELECT auth.uid() AS uid)) AND ((ba.status)::text = 'active'::text) AND (ba.deleted_at IS NULL))))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER')))))
;
CREATE POLICY "merged_raw_records_insert" ON public.raw_records AS PERMISSIVE FOR INSERT TO public
  WITH CHECK (((((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR (((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR ((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER')))))
;
CREATE POLICY "merged_raw_records_update" ON public.raw_records AS PERMISSIVE FOR UPDATE TO public
  USING (((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR ((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER'))) OR (((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER')))))
  WITH CHECK (((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR ((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER'))) OR (((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER')))))
;
CREATE POLICY "merged_raw_records_delete" ON public.raw_records AS PERMISSIVE FOR DELETE TO public
  USING (((((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR (((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR ((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER')))))
;
DROP POLICY IF EXISTS "raw_records_delete_tenant" ON public.raw_records;
DROP POLICY IF EXISTS "raw_records_insert_tenant" ON public.raw_records;
DROP POLICY IF EXISTS "raw_records_isolation" ON public.raw_records;
DROP POLICY IF EXISTS "raw_records_modify_service" ON public.raw_records;
DROP POLICY IF EXISTS "raw_records_select_tenant" ON public.raw_records;
DROP POLICY IF EXISTS "raw_records_update_tenant" ON public.raw_records;
-- =============== receipt_items ===============
CREATE POLICY "merged_receipt_items_select" ON public.receipt_items AS PERMISSIVE FOR SELECT TO public
  USING (((((receipt_id IN ( SELECT receipts.id
   FROM receipts
  WHERE (receipts.tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR ((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER'))) OR (((EXISTS ( SELECT 1
   FROM receipts r
  WHERE ((r.id = receipt_items.receipt_id) AND (r.tenant_id IN ( SELECT ba.tenant_id
           FROM billing_accounts ba
          WHERE ((ba.user_id = ( SELECT auth.uid() AS uid)) AND ((ba.status)::text = 'active'::text) AND (ba.deleted_at IS NULL)))))))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER')))))
;
CREATE POLICY "merged_receipt_items_insert" ON public.receipt_items AS PERMISSIVE FOR INSERT TO public
  WITH CHECK (((((EXISTS ( SELECT 1
   FROM receipts r
  WHERE ((r.id = receipt_items.receipt_id) AND (r.tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR (((receipt_id IN ( SELECT receipts.id
   FROM receipts
  WHERE (receipts.tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR ((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER')))))
;
CREATE POLICY "merged_receipt_items_update" ON public.receipt_items AS PERMISSIVE FOR UPDATE TO public
  USING (((((receipt_id IN ( SELECT receipts.id
   FROM receipts
  WHERE (receipts.tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR ((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER'))) OR (((EXISTS ( SELECT 1
   FROM receipts r
  WHERE ((r.id = receipt_items.receipt_id) AND (r.tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER')))))
  WITH CHECK (((((receipt_id IN ( SELECT receipts.id
   FROM receipts
  WHERE (receipts.tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR ((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER'))) OR (((EXISTS ( SELECT 1
   FROM receipts r
  WHERE ((r.id = receipt_items.receipt_id) AND (r.tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER')))))
;
CREATE POLICY "merged_receipt_items_delete" ON public.receipt_items AS PERMISSIVE FOR DELETE TO public
  USING (((((EXISTS ( SELECT 1
   FROM receipts r
  WHERE ((r.id = receipt_items.receipt_id) AND (r.tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR (((receipt_id IN ( SELECT receipts.id
   FROM receipts
  WHERE (receipts.tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR ((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER')))))
;
DROP POLICY IF EXISTS "receipt_items_delete_tenant" ON public.receipt_items;
DROP POLICY IF EXISTS "receipt_items_insert_tenant" ON public.receipt_items;
DROP POLICY IF EXISTS "receipt_items_isolation" ON public.receipt_items;
DROP POLICY IF EXISTS "receipt_items_modify_service" ON public.receipt_items;
DROP POLICY IF EXISTS "receipt_items_select_tenant" ON public.receipt_items;
DROP POLICY IF EXISTS "receipt_items_update_tenant" ON public.receipt_items;
-- =============== receipt_uploads ===============
CREATE POLICY "merged_receipt_uploads_select" ON public.receipt_uploads AS PERMISSIVE FOR SELECT TO authenticated
  USING ((((billing_account_id IN ( SELECT billing_accounts.id
   FROM billing_accounts
  WHERE (billing_accounts.user_id = ( SELECT auth.uid() AS uid))))) OR (((EXISTS ( SELECT 1
   FROM billing_accounts ba
  WHERE ((ba.id = receipt_uploads.billing_account_id) AND ((ba.user_id = ( SELECT auth.uid() AS uid)) OR (ba.tenant_id IN ( SELECT tu.tenant_id
           FROM tenant_users tu
          WHERE (tu.user_id = ( SELECT auth.uid() AS uid)))))))) OR (EXISTS ( SELECT 1
   FROM api_keys ak
  WHERE ((ak.id = receipt_uploads.api_key_id) AND (ak.user_id = ( SELECT auth.uid() AS uid)))))))))
;
CREATE POLICY "merged_receipt_uploads_insert" ON public.receipt_uploads AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((((EXISTS ( SELECT 1
   FROM billing_accounts ba
  WHERE ((ba.id = receipt_uploads.billing_account_id) AND ((ba.user_id = ( SELECT auth.uid() AS uid)) OR (ba.tenant_id IN ( SELECT tu.tenant_id
           FROM tenant_users tu
          WHERE (tu.user_id = ( SELECT auth.uid() AS uid)))))))) OR (EXISTS ( SELECT 1
   FROM api_keys ak
  WHERE ((ak.id = receipt_uploads.api_key_id) AND (ak.user_id = ( SELECT auth.uid() AS uid))))))))
;
CREATE POLICY "merged_receipt_uploads_update" ON public.receipt_uploads AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((((EXISTS ( SELECT 1
   FROM billing_accounts ba
  WHERE ((ba.id = receipt_uploads.billing_account_id) AND ((ba.user_id = ( SELECT auth.uid() AS uid)) OR (ba.tenant_id IN ( SELECT tu.tenant_id
           FROM tenant_users tu
          WHERE (tu.user_id = ( SELECT auth.uid() AS uid)))))))) OR (EXISTS ( SELECT 1
   FROM api_keys ak
  WHERE ((ak.id = receipt_uploads.api_key_id) AND (ak.user_id = ( SELECT auth.uid() AS uid))))))))
  WITH CHECK ((((EXISTS ( SELECT 1
   FROM billing_accounts ba
  WHERE ((ba.id = receipt_uploads.billing_account_id) AND ((ba.user_id = ( SELECT auth.uid() AS uid)) OR (ba.tenant_id IN ( SELECT tu.tenant_id
           FROM tenant_users tu
          WHERE (tu.user_id = ( SELECT auth.uid() AS uid)))))))) OR (EXISTS ( SELECT 1
   FROM api_keys ak
  WHERE ((ak.id = receipt_uploads.api_key_id) AND (ak.user_id = ( SELECT auth.uid() AS uid))))))))
;
CREATE POLICY "merged_receipt_uploads_delete" ON public.receipt_uploads AS PERMISSIVE FOR DELETE TO authenticated
  USING ((((EXISTS ( SELECT 1
   FROM billing_accounts ba
  WHERE ((ba.id = receipt_uploads.billing_account_id) AND ((ba.user_id = ( SELECT auth.uid() AS uid)) OR (ba.tenant_id IN ( SELECT tenant_users.tenant_id
           FROM tenant_users
          WHERE (tenant_users.user_id = ( SELECT auth.uid() AS uid)))))))) OR (EXISTS ( SELECT 1
   FROM api_keys ak
  WHERE ((ak.id = receipt_uploads.api_key_id) AND (ak.user_id = ( SELECT auth.uid() AS uid))))))))
;
DROP POLICY IF EXISTS "receipt_uploads_delete_authenticated" ON public.receipt_uploads;
DROP POLICY IF EXISTS "receipt_uploads_insert_unified" ON public.receipt_uploads;
DROP POLICY IF EXISTS "receipt_uploads_select" ON public.receipt_uploads;
DROP POLICY IF EXISTS "receipt_uploads_select_unified" ON public.receipt_uploads;
DROP POLICY IF EXISTS "receipt_uploads_update_unified" ON public.receipt_uploads;
-- =============== recon_audits ===============
CREATE POLICY "merged_recon_audits_select" ON public.recon_audits AS PERMISSIVE FOR SELECT TO authenticated
  USING ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
CREATE POLICY "merged_recon_audits_insert" ON public.recon_audits AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
CREATE POLICY "merged_recon_audits_update" ON public.recon_audits AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
  WITH CHECK ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
CREATE POLICY "merged_recon_audits_delete" ON public.recon_audits AS PERMISSIVE FOR DELETE TO authenticated
  USING ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
DROP POLICY IF EXISTS "recon_audits_isolation" ON public.recon_audits;
DROP POLICY IF EXISTS "tenant_delete" ON public.recon_audits;
DROP POLICY IF EXISTS "tenant_insert" ON public.recon_audits;
DROP POLICY IF EXISTS "tenant_select" ON public.recon_audits;
DROP POLICY IF EXISTS "tenant_update" ON public.recon_audits;
-- =============== recon_jobs ===============
CREATE POLICY "merged_recon_jobs_select" ON public.recon_jobs AS PERMISSIVE FOR SELECT TO authenticated
  USING (((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids)) OR (tenant_id IN ( SELECT COALESCE(billing_accounts.tenant_id, billing_accounts.id) AS "coalesce"
   FROM billing_accounts
  WHERE (billing_accounts.user_id = ( SELECT auth.uid() AS uid)))))) OR ((tenant_id IN ( SELECT ba.tenant_id
   FROM billing_accounts ba
  WHERE ((ba.user_id = ( SELECT auth.uid() AS uid)) AND ((ba.status)::text = 'active'::text) AND (ba.deleted_at IS NULL)))))))
;
CREATE POLICY "merged_recon_jobs_insert" ON public.recon_jobs AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK (((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids)) OR (tenant_id IN ( SELECT COALESCE(billing_accounts.tenant_id, billing_accounts.id) AS "coalesce"
   FROM billing_accounts
  WHERE (billing_accounts.user_id = ( SELECT auth.uid() AS uid)))))) OR (((tenant_id IN ( SELECT ba.tenant_id
   FROM billing_accounts ba
  WHERE ((ba.user_id = ( SELECT auth.uid() AS uid)) AND ((ba.status)::text = 'active'::text) AND (ba.deleted_at IS NULL)))) AND has_active_subscription(( SELECT auth.uid() AS uid))))))
;
CREATE POLICY "merged_recon_jobs_update" ON public.recon_jobs AS PERMISSIVE FOR UPDATE TO authenticated
  USING (((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids)) OR (tenant_id IN ( SELECT COALESCE(billing_accounts.tenant_id, billing_accounts.id) AS "coalesce"
   FROM billing_accounts
  WHERE (billing_accounts.user_id = ( SELECT auth.uid() AS uid)))))) OR ((tenant_id IN ( SELECT ba.tenant_id
   FROM billing_accounts ba
  WHERE ((ba.user_id = ( SELECT auth.uid() AS uid)) AND ((ba.status)::text = 'active'::text) AND (ba.deleted_at IS NULL)))))))
  WITH CHECK (((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids)) OR (tenant_id IN ( SELECT COALESCE(billing_accounts.tenant_id, billing_accounts.id) AS "coalesce"
   FROM billing_accounts
  WHERE (billing_accounts.user_id = ( SELECT auth.uid() AS uid)))))) OR ((tenant_id IN ( SELECT ba.tenant_id
   FROM billing_accounts ba
  WHERE ((ba.user_id = ( SELECT auth.uid() AS uid)) AND ((ba.status)::text = 'active'::text) AND (ba.deleted_at IS NULL)))))))
;
CREATE POLICY "merged_recon_jobs_delete" ON public.recon_jobs AS PERMISSIVE FOR DELETE TO authenticated
  USING (((tenant_id IN ( SELECT ba.tenant_id
   FROM billing_accounts ba
  WHERE ((ba.user_id = ( SELECT auth.uid() AS uid)) AND ((ba.status)::text = 'active'::text) AND (ba.deleted_at IS NULL))))))
;
DROP POLICY IF EXISTS "recon_jobs_insert" ON public.recon_jobs;
DROP POLICY IF EXISTS "recon_jobs_select" ON public.recon_jobs;
DROP POLICY IF EXISTS "recon_jobs_update" ON public.recon_jobs;
DROP POLICY IF EXISTS "tenant_isolation_delete" ON public.recon_jobs;
DROP POLICY IF EXISTS "tenant_isolation_insert" ON public.recon_jobs;
DROP POLICY IF EXISTS "tenant_isolation_select" ON public.recon_jobs;
DROP POLICY IF EXISTS "tenant_isolation_update" ON public.recon_jobs;
-- =============== recon_results ===============
CREATE POLICY "merged_recon_results_select" ON public.recon_results AS PERMISSIVE FOR SELECT TO authenticated
  USING (((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids)) OR (tenant_id IN ( SELECT COALESCE(billing_accounts.tenant_id, billing_accounts.id) AS "coalesce"
   FROM billing_accounts
  WHERE (billing_accounts.user_id = ( SELECT auth.uid() AS uid)))))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
CREATE POLICY "merged_recon_results_insert" ON public.recon_results AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK (((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))))
;
CREATE POLICY "merged_recon_results_update" ON public.recon_results AS PERMISSIVE FOR UPDATE TO authenticated
  USING (((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))))
  WITH CHECK (((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))))
;
CREATE POLICY "merged_recon_results_delete" ON public.recon_results AS PERMISSIVE FOR DELETE TO authenticated
  USING (((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))))
;
DROP POLICY IF EXISTS "recon_results_select" ON public.recon_results;
DROP POLICY IF EXISTS "tenant_delete" ON public.recon_results;
DROP POLICY IF EXISTS "tenant_insert" ON public.recon_results;
DROP POLICY IF EXISTS "tenant_select" ON public.recon_results;
DROP POLICY IF EXISTS "tenant_update" ON public.recon_results;
-- =============== recon_templates ===============
CREATE POLICY "merged_recon_templates_select" ON public.recon_templates AS PERMISSIVE FOR SELECT TO authenticated
  USING (((((is_public = true) OR (is_system = true) OR (tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids)))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
CREATE POLICY "merged_recon_templates_insert" ON public.recon_templates AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
CREATE POLICY "merged_recon_templates_update" ON public.recon_templates AS PERMISSIVE FOR UPDATE TO authenticated
  USING (((((is_system = false) AND (tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids)))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
  WITH CHECK (((((is_system = false) AND (tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids)))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
CREATE POLICY "merged_recon_templates_delete" ON public.recon_templates AS PERMISSIVE FOR DELETE TO authenticated
  USING (((((is_system = false) AND (tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids)))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
DROP POLICY IF EXISTS "recon_templates_delete" ON public.recon_templates;
DROP POLICY IF EXISTS "recon_templates_insert" ON public.recon_templates;
DROP POLICY IF EXISTS "recon_templates_select" ON public.recon_templates;
DROP POLICY IF EXISTS "recon_templates_update" ON public.recon_templates;
DROP POLICY IF EXISTS "tenant_delete" ON public.recon_templates;
DROP POLICY IF EXISTS "tenant_insert" ON public.recon_templates;
DROP POLICY IF EXISTS "tenant_select" ON public.recon_templates;
DROP POLICY IF EXISTS "tenant_update" ON public.recon_templates;
-- =============== reconciliation_matches ===============
CREATE POLICY "merged_reconciliation_matches_select" ON public.reconciliation_matches AS PERMISSIVE FOR SELECT TO public
  USING (((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR ((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER'))) OR (((EXISTS ( SELECT 1
   FROM reconciliation_runs rr
  WHERE ((rr.id = reconciliation_matches.run_id) AND (rr.tenant_id IN ( SELECT ba.tenant_id
           FROM billing_accounts ba
          WHERE ((ba.user_id = ( SELECT auth.uid() AS uid)) AND ((ba.status)::text = 'active'::text) AND (ba.deleted_at IS NULL)))))))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER')))))
;
CREATE POLICY "merged_reconciliation_matches_insert" ON public.reconciliation_matches AS PERMISSIVE FOR INSERT TO public
  WITH CHECK (((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR ((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER')))))
;
CREATE POLICY "merged_reconciliation_matches_update" ON public.reconciliation_matches AS PERMISSIVE FOR UPDATE TO public
  USING (((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR ((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER')))))
  WITH CHECK (((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR ((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER')))))
;
CREATE POLICY "merged_reconciliation_matches_delete" ON public.reconciliation_matches AS PERMISSIVE FOR DELETE TO public
  USING (((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR ((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER')))))
;
DROP POLICY IF EXISTS "reconciliation_matches_isolation" ON public.reconciliation_matches;
DROP POLICY IF EXISTS "reconciliation_matches_modify_service" ON public.reconciliation_matches;
DROP POLICY IF EXISTS "reconciliation_matches_select_tenant" ON public.reconciliation_matches;
-- =============== reconciliation_runs ===============
CREATE POLICY "merged_reconciliation_runs_select" ON public.reconciliation_runs AS PERMISSIVE FOR SELECT TO public
  USING (((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR ((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER'))) OR (((tenant_id IN ( SELECT ba.tenant_id
   FROM billing_accounts ba
  WHERE ((ba.user_id = ( SELECT auth.uid() AS uid)) AND ((ba.status)::text = 'active'::text) AND (ba.deleted_at IS NULL))))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER')))))
;
CREATE POLICY "merged_reconciliation_runs_insert" ON public.reconciliation_runs AS PERMISSIVE FOR INSERT TO public
  WITH CHECK (((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR ((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER')))))
;
CREATE POLICY "merged_reconciliation_runs_update" ON public.reconciliation_runs AS PERMISSIVE FOR UPDATE TO public
  USING (((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR ((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER')))))
  WITH CHECK (((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR ((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER')))))
;
CREATE POLICY "merged_reconciliation_runs_delete" ON public.reconciliation_runs AS PERMISSIVE FOR DELETE TO public
  USING (((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR ((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER')))))
;
DROP POLICY IF EXISTS "reconciliation_runs_isolation" ON public.reconciliation_runs;
DROP POLICY IF EXISTS "reconciliation_runs_modify_service" ON public.reconciliation_runs;
DROP POLICY IF EXISTS "reconciliation_runs_select_tenant" ON public.reconciliation_runs;
-- =============== stripe_events ===============
CREATE POLICY "merged_stripe_events_select" ON public.stripe_events AS PERMISSIVE FOR SELECT TO authenticated
  USING ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
CREATE POLICY "merged_stripe_events_insert" ON public.stripe_events AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
CREATE POLICY "merged_stripe_events_update" ON public.stripe_events AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
  WITH CHECK ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
CREATE POLICY "merged_stripe_events_delete" ON public.stripe_events AS PERMISSIVE FOR DELETE TO authenticated
  USING ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[]))))))
;
DROP POLICY IF EXISTS "stripe_events_isolation" ON public.stripe_events;
DROP POLICY IF EXISTS "tenant_delete" ON public.stripe_events;
DROP POLICY IF EXISTS "tenant_insert" ON public.stripe_events;
DROP POLICY IF EXISTS "tenant_select" ON public.stripe_events;
DROP POLICY IF EXISTS "tenant_update" ON public.stripe_events;
-- =============== tenants ===============
CREATE POLICY "merged_tenants_select" ON public.tenants AS PERMISSIVE FOR SELECT TO public
  USING ((((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER'))) OR ((((id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids)) OR (billing_account_id IN ( SELECT ba.id
   FROM billing_accounts ba
  WHERE (ba.user_id = ( SELECT auth.uid() AS uid)))) OR (id IN ( SELECT tu.tenant_id
   FROM tenant_users tu
  WHERE (tu.user_id = ( SELECT auth.uid() AS uid)))))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))) OR (((id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER')))))
;
CREATE POLICY "merged_tenants_insert" ON public.tenants AS PERMISSIVE FOR INSERT TO public
  WITH CHECK (((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER'))))
;
CREATE POLICY "merged_tenants_update" ON public.tenants AS PERMISSIVE FOR UPDATE TO public
  USING (((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER'))))
  WITH CHECK (((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER'))))
;
CREATE POLICY "merged_tenants_delete" ON public.tenants AS PERMISSIVE FOR DELETE TO public
  USING (((true) AND (pg_has_role(current_user, 'service_role', 'MEMBER'))))
;
DROP POLICY IF EXISTS "Service role can manage tenants" ON public.tenants;
DROP POLICY IF EXISTS "tenants_select_authenticated" ON public.tenants;
DROP POLICY IF EXISTS "tenants_select_tenant" ON public.tenants;
-- =============== transform_recipes ===============
CREATE POLICY "merged_transform_recipes_select" ON public.transform_recipes AS PERMISSIVE FOR SELECT TO authenticated
  USING ((((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))) OR (((is_public = true) OR (is_system = true) OR (tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))))))
;
CREATE POLICY "merged_transform_recipes_insert" ON public.transform_recipes AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))) OR ((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids)))))
;
CREATE POLICY "merged_transform_recipes_update" ON public.transform_recipes AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))) OR (((is_public = true) OR (is_system = true) OR (tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))))))
  WITH CHECK ((((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))) OR ((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids)))))
;
CREATE POLICY "merged_transform_recipes_delete" ON public.transform_recipes AS PERMISSIVE FOR DELETE TO authenticated
  USING ((((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))) OR (((is_public = true) OR (is_system = true) OR (tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))))))
;
DROP POLICY IF EXISTS "tenant_delete" ON public.transform_recipes;
DROP POLICY IF EXISTS "tenant_insert" ON public.transform_recipes;
DROP POLICY IF EXISTS "tenant_select" ON public.transform_recipes;
DROP POLICY IF EXISTS "tenant_update" ON public.transform_recipes;
DROP POLICY IF EXISTS "transform_recipes_isolation" ON public.transform_recipes;
-- =============== usage_aggregate_daily ===============
CREATE POLICY "merged_usage_aggregate_daily_select" ON public.usage_aggregate_daily AS PERMISSIVE FOR SELECT TO authenticated
  USING ((((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))) OR ((billing_account_id IN ( SELECT billing_accounts.id
   FROM billing_accounts
  WHERE (billing_accounts.user_id = ( SELECT auth.uid() AS uid)))))))
;
CREATE POLICY "merged_usage_aggregate_daily_insert" ON public.usage_aggregate_daily AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK (((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))))
;
CREATE POLICY "merged_usage_aggregate_daily_update" ON public.usage_aggregate_daily AS PERMISSIVE FOR UPDATE TO authenticated
  USING (((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))))
  WITH CHECK (((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))))
;
CREATE POLICY "merged_usage_aggregate_daily_delete" ON public.usage_aggregate_daily AS PERMISSIVE FOR DELETE TO authenticated
  USING (((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))))
;
DROP POLICY IF EXISTS "tenant_delete" ON public.usage_aggregate_daily;
DROP POLICY IF EXISTS "tenant_insert" ON public.usage_aggregate_daily;
DROP POLICY IF EXISTS "tenant_select" ON public.usage_aggregate_daily;
DROP POLICY IF EXISTS "tenant_update" ON public.usage_aggregate_daily;
DROP POLICY IF EXISTS "usage_aggregate_daily_select" ON public.usage_aggregate_daily;
-- =============== users ===============
CREATE POLICY "merged_users_select" ON public.users AS PERMISSIVE FOR SELECT TO public
  USING ((((( SELECT auth.uid() AS uid) = id)) OR (((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER')))))
;
CREATE POLICY "merged_users_insert" ON public.users AS PERMISSIVE FOR INSERT TO public
  WITH CHECK ((((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))))
;
CREATE POLICY "merged_users_update" ON public.users AS PERMISSIVE FOR UPDATE TO public
  USING ((((( SELECT auth.uid() AS uid) = id)) OR (((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER')))))
  WITH CHECK ((((( SELECT auth.uid() AS uid) = id)) OR (((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER')))))
;
CREATE POLICY "merged_users_delete" ON public.users AS PERMISSIVE FOR DELETE TO public
  USING ((((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))) AND (pg_has_role(current_user, 'authenticated', 'MEMBER'))))
;
DROP POLICY IF EXISTS "Users can update own profile" ON public.users;
DROP POLICY IF EXISTS "Users can view own profile" ON public.users;
DROP POLICY IF EXISTS "tenant_delete" ON public.users;
DROP POLICY IF EXISTS "tenant_insert" ON public.users;
DROP POLICY IF EXISTS "tenant_select" ON public.users;
DROP POLICY IF EXISTS "tenant_update" ON public.users;
-- =============== validation_rules ===============
CREATE POLICY "merged_validation_rules_select" ON public.validation_rules AS PERMISSIVE FOR SELECT TO authenticated
  USING ((((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))) OR (((is_public = true) OR (is_system = true) OR (tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))))))
;
CREATE POLICY "merged_validation_rules_insert" ON public.validation_rules AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))) OR ((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids)))))
;
CREATE POLICY "merged_validation_rules_update" ON public.validation_rules AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))) OR (((is_public = true) OR (is_system = true) OR (tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))))))
  WITH CHECK ((((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))) OR ((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids)))))
;
CREATE POLICY "merged_validation_rules_delete" ON public.validation_rules AS PERMISSIVE FOR DELETE TO authenticated
  USING ((((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))) OR (((is_public = true) OR (is_system = true) OR (tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))))))
;
DROP POLICY IF EXISTS "tenant_delete" ON public.validation_rules;
DROP POLICY IF EXISTS "tenant_insert" ON public.validation_rules;
DROP POLICY IF EXISTS "tenant_select" ON public.validation_rules;
DROP POLICY IF EXISTS "tenant_update" ON public.validation_rules;
DROP POLICY IF EXISTS "validation_rules_isolation" ON public.validation_rules;
-- =============== webhook_deliveries ===============
CREATE POLICY "merged_webhook_deliveries_select" ON public.webhook_deliveries AS PERMISSIVE FOR SELECT TO authenticated
  USING ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = current_tenant()))))
;
CREATE POLICY "merged_webhook_deliveries_insert" ON public.webhook_deliveries AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK (((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))))
;
CREATE POLICY "merged_webhook_deliveries_update" ON public.webhook_deliveries AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = current_tenant()))))
  WITH CHECK ((((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))) OR ((tenant_id = current_tenant()))))
;
CREATE POLICY "merged_webhook_deliveries_delete" ON public.webhook_deliveries AS PERMISSIVE FOR DELETE TO authenticated
  USING (((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids))))
;
DROP POLICY IF EXISTS "webhook_deliveries_isolation" ON public.webhook_deliveries;
DROP POLICY IF EXISTS "webhook_deliveries_select" ON public.webhook_deliveries;
DROP POLICY IF EXISTS "webhook_deliveries_update" ON public.webhook_deliveries;
-- =============== webhooks ===============
CREATE POLICY "merged_webhooks_select" ON public.webhooks AS PERMISSIVE FOR SELECT TO authenticated
  USING ((((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))) OR ((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids)))))
;
CREATE POLICY "merged_webhooks_insert" ON public.webhooks AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))) OR ((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids)))))
;
CREATE POLICY "merged_webhooks_update" ON public.webhooks AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))) OR ((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids)))))
  WITH CHECK ((((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))) OR ((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids)))))
;
CREATE POLICY "merged_webhooks_delete" ON public.webhooks AS PERMISSIVE FOR DELETE TO authenticated
  USING ((((tenant_id = ANY (COALESCE(( SELECT app_private.current_tenant_ids() AS current_tenant_ids), ARRAY[]::uuid[])))) OR ((tenant_id IN ( SELECT get_user_tenant_ids() AS get_user_tenant_ids)))))
;
DROP POLICY IF EXISTS "tenant_delete" ON public.webhooks;
DROP POLICY IF EXISTS "tenant_insert" ON public.webhooks;
DROP POLICY IF EXISTS "tenant_select" ON public.webhooks;
DROP POLICY IF EXISTS "tenant_update" ON public.webhooks;
DROP POLICY IF EXISTS "webhooks_delete" ON public.webhooks;
DROP POLICY IF EXISTS "webhooks_insert" ON public.webhooks;
DROP POLICY IF EXISTS "webhooks_select" ON public.webhooks;
DROP POLICY IF EXISTS "webhooks_update" ON public.webhooks;
