-- 20260107000000_remainder_consolidation.sql
-- Consolidated Idempotent Migration for Settler Monorepo
-- Generated by Gemini 3 System Auditor

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

-- 1. Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;
CREATE EXTENSION IF NOT EXISTS "pg_trgm" WITH SCHEMA public;

-- 2. Tables & Columns (Idempotent)

DO $$ 
BEGIN

  -- BILLING ACCOUNTS
  CREATE TABLE IF NOT EXISTS public.billing_accounts (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    user_id uuid NOT NULL,
    tenant_id uuid,
    stripe_customer_id text,
    stripe_account_id text,
    email text NOT NULL,
    name text,
    address jsonb,
    tax_id text,
    currency text DEFAULT 'usd',
    status text DEFAULT 'active',
    metadata jsonb DEFAULT '{}',
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz
  );
  -- Add columns if missing
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='billing_accounts' AND column_name='tenant_id') THEN
    ALTER TABLE public.billing_accounts ADD COLUMN tenant_id uuid;
  END IF;

  -- SUBSCRIPTIONS
  CREATE TABLE IF NOT EXISTS public.subscriptions (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    billing_account_id uuid REFERENCES public.billing_accounts(id) ON DELETE CASCADE,
    stripe_subscription_id text,
    stripe_price_id text,
    plan_id text NOT NULL,
    plan_name text NOT NULL,
    status text NOT NULL,
    current_period_start timestamptz NOT NULL,
    current_period_end timestamptz NOT NULL,
    cancel_at_period_end boolean DEFAULT false,
    cancelled_at timestamptz,
    trial_start timestamptz,
    trial_end timestamptz,
    metadata jsonb,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
  );

  -- TENANTS
  CREATE TABLE IF NOT EXISTS public.tenants (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    billing_account_id uuid REFERENCES public.billing_accounts(id) ON DELETE SET NULL,
    slug text UNIQUE NOT NULL,
    primary_domain text,
    custom_domain text,
    name text NOT NULL,
    is_active boolean DEFAULT true,
    metadata jsonb DEFAULT '{}',
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
  );

  -- RECON JOBS
  CREATE TABLE IF NOT EXISTS public.recon_jobs (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    tenant_id uuid NOT NULL, -- Logical FK, enforce via app or RLS
    user_id uuid NOT NULL,
    name text NOT NULL,
    description text,
    template_id uuid,
    source_adapter text NOT NULL,
    source_config_encrypted text NOT NULL,
    target_adapter text NOT NULL,
    target_config_encrypted text NOT NULL,
    mapping_template_id uuid,
    transform_recipe_id uuid,
    validation_rules jsonb DEFAULT '[]',
    recon_strategy text DEFAULT 'deterministic',
    schedule_cron text,
    schedule_timezone text DEFAULT 'UTC',
    status text DEFAULT 'active',
    version int DEFAULT 1,
    metadata jsonb DEFAULT '{}',
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz
  );

  -- RECON RESULTS
  CREATE TABLE IF NOT EXISTS public.recon_results (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    recon_job_id uuid REFERENCES public.recon_jobs(id) ON DELETE CASCADE,
    tenant_id uuid NOT NULL,
    execution_id uuid,
    status text DEFAULT 'running',
    started_at timestamptz DEFAULT now(),
    completed_at timestamptz,
    source_count int DEFAULT 0,
    target_count int DEFAULT 0,
    matched_count int DEFAULT 0,
    unmatched_source_count int DEFAULT 0,
    unmatched_target_count int DEFAULT 0,
    conflict_count int DEFAULT 0,
    total_amount_source numeric(15,2),
    total_amount_target numeric(15,2),
    total_amount_matched numeric(15,2),
    total_amount_unmatched numeric(15,2),
    currency text,
    confidence_avg numeric(5,4),
    confidence_min numeric(5,4),
    confidence_max numeric(5,4),
    duration_ms bigint,
    error_message text,
    error_stack text,
    summary jsonb DEFAULT '{}',
    metadata jsonb DEFAULT '{}',
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
  );

  -- AUDIT LOGS
  CREATE TABLE IF NOT EXISTS public.audit_logs (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    user_id uuid,
    billing_account_id uuid,
    tenant_id uuid,
    action text NOT NULL,
    resource_type text NOT NULL,
    resource_id uuid,
    changes jsonb,
    ip_address text,
    user_agent text,
    metadata jsonb DEFAULT '{}',
    created_at timestamptz DEFAULT now()
  );

  -- FEATURE FLAGS
  CREATE TABLE IF NOT EXISTS public.feature_flags (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    billing_account_id uuid,
    project_id uuid,
    key text NOT NULL,
    name text NOT NULL,
    description text,
    type text DEFAULT 'boolean',
    is_global boolean DEFAULT false,
    default_value jsonb,
    metadata jsonb DEFAULT '{}',
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz
  );

  -- INGESTION SOURCES
  CREATE TABLE IF NOT EXISTS public.ingestion_sources (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    tenant_id uuid NOT NULL,
    user_id uuid NOT NULL,
    name text NOT NULL,
    type text NOT NULL,
    connector_type text,
    config_encrypted text,
    config_metadata jsonb DEFAULT '{}',
    status text DEFAULT 'active',
    last_sync_at timestamptz,
    last_sync_status text,
    last_sync_error text,
    sync_schedule text,
    metadata jsonb DEFAULT '{}',
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz
  );

  -- RECEIPTS
  CREATE TABLE IF NOT EXISTS public.receipt_uploads (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    api_key_id uuid,
    billing_account_id uuid,
    storage_location text NOT NULL,
    original_filename text NOT NULL,
    mime_type text NOT NULL,
    size_bytes int NOT NULL,
    status text DEFAULT 'pending',
    error_message text,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
  );

END $$;

-- 3. RLS Enablement (Idempotent)

ALTER TABLE public.billing_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recon_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recon_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feature_flags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ingestion_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.receipt_uploads ENABLE ROW LEVEL SECURITY;

-- 4. Policies (Idempotent via DO blocks)

DO $$
BEGIN
  -- Billing Accounts: Users view their own
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users view own billing account' AND tablename = 'billing_accounts') THEN
    CREATE POLICY "Users view own billing account" ON public.billing_accounts
      FOR SELECT USING (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users update own billing account' AND tablename = 'billing_accounts') THEN
    CREATE POLICY "Users update own billing account" ON public.billing_accounts
      FOR UPDATE USING (auth.uid() = user_id);
  END IF;

  -- Tenants: Users view tenants linked to their billing account
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users view owned tenants' AND tablename = 'tenants') THEN
    CREATE POLICY "Users view owned tenants" ON public.tenants
      FOR SELECT USING (
        EXISTS (
          SELECT 1 FROM public.billing_accounts ba 
          WHERE ba.id = tenants.billing_account_id 
          AND ba.user_id = auth.uid()
        )
      );
  END IF;
  
  -- Tenants: Public read for domain resolution (needed for middleware/site builder)
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public read for domain resolution' AND tablename = 'tenants') THEN
    CREATE POLICY "Public read for domain resolution" ON public.tenants
      FOR SELECT USING (true); 
      -- Note: This is broad, but necessary for multi-tenant domain resolution on edge. 
      -- Ideally scoped to specific columns, but RLS is row-level.
      -- Real-world app might use a separate 'domains' table or 'security definer' function to lookup without exposing all tenant data.
      -- For audit safety, we keep it as is but flag it.
  END IF;

  -- Recon Jobs: Users view their own
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users view own recon jobs' AND tablename = 'recon_jobs') THEN
    CREATE POLICY "Users view own recon jobs" ON public.recon_jobs
      FOR ALL USING (auth.uid() = user_id);
  END IF;

  -- Ingestion: Users view their own
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users view own ingestion sources' AND tablename = 'ingestion_sources') THEN
    CREATE POLICY "Users view own ingestion sources" ON public.ingestion_sources
      FOR ALL USING (auth.uid() = user_id);
  END IF;

END $$;

-- 5. Indexes (Idempotent)

CREATE INDEX IF NOT EXISTS billing_accounts_user_id_idx ON public.billing_accounts(user_id);
CREATE INDEX IF NOT EXISTS billing_accounts_tenant_id_idx ON public.billing_accounts(tenant_id);
CREATE INDEX IF NOT EXISTS subscriptions_billing_account_id_idx ON public.subscriptions(billing_account_id);
CREATE INDEX IF NOT EXISTS tenants_slug_idx ON public.tenants(slug);
CREATE INDEX IF NOT EXISTS tenants_primary_domain_idx ON public.tenants(primary_domain);
CREATE INDEX IF NOT EXISTS recon_jobs_user_id_idx ON public.recon_jobs(user_id);
CREATE INDEX IF NOT EXISTS recon_jobs_tenant_id_idx ON public.recon_jobs(tenant_id);

-- 6. Helper Functions (Immutable Search Path)

CREATE OR REPLACE FUNCTION public.get_current_user_id()
RETURNS uuid
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT auth.uid();
$$;

-- 7. Realtime (Idempotent)

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' 
    AND schemaname = 'public' 
    AND tablename = 'recon_results'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.recon_results;
  END IF;
END $$;
