import Link from "next/link";
import { ConsolePageHeader } from "@/components/console/ConsolePageHeader";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

const surfaces = [
  {
    title: "Evidence browser",
    description:
      "Inspect proof chains and hash-linked evidence generated by reconciliation activity.",
    href: "/proof-explorer",
    cta: "Open browser",
  },
  {
    title: "Verification receipts",
    description: "Review run-level verification receipts and evidence hash summaries.",
    href: "/console/receipts-hash",
    cta: "Open receipts",
  },
];

export default function ProofExplorerPage() {
  return (
    <div className="space-y-6">
      <ConsolePageHeader
        title="Proof Explorer"
        description="Tenant-scoped proof and verification evidence for deterministic audit trails."
      />

      <section aria-label="Proof explorer surfaces" className="grid gap-4 md:grid-cols-2">
        {surfaces.map((surface) => (
          <Card key={surface.href}>
            <CardHeader>
              <CardTitle>{surface.title}</CardTitle>
              <CardDescription>{surface.description}</CardDescription>
            </CardHeader>
            <CardContent>
              <Button asChild variant="outline" className="w-full sm:w-auto">
                <Link href={surface.href}>{surface.cta}</Link>
              </Button>
            </CardContent>
          </Card>
        ))}
      </section>
    </div>
  );
}
